
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const CallTranscriptStatus = {
  NOT_STARTED: 'NOT_STARTED',
  PROCESSING: 'PROCESSING',
  READY: 'READY',
  ERROR: 'ERROR'
} as const

export type CallTranscriptStatus = (typeof CallTranscriptStatus)[keyof typeof CallTranscriptStatus]


export const AbhiCallEpisodeDraftStatus = {
  PROCESSING: 'PROCESSING',
  READY: 'READY',
  ERROR: 'ERROR',
  CANCELLED: 'CANCELLED'
} as const

export type AbhiCallEpisodeDraftStatus = (typeof AbhiCallEpisodeDraftStatus)[keyof typeof AbhiCallEpisodeDraftStatus]


export const AbhiCallEpisodeDraftStep = {
  STARTED: 'STARTED',
  GENERATING_AUDIO: 'GENERATING_AUDIO',
  TRANSCRIBING: 'TRANSCRIBING',
  GENERATING_METADATA: 'GENERATING_METADATA',
  DONE: 'DONE'
} as const

export type AbhiCallEpisodeDraftStep = (typeof AbhiCallEpisodeDraftStep)[keyof typeof AbhiCallEpisodeDraftStep]
