
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AbhiCallEpisodeDraft` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AbhiCallEpisodeDraft
 * 
 */
export type AbhiCallEpisodeDraftModel = runtime.Types.Result.DefaultSelection<Prisma.$AbhiCallEpisodeDraftPayload>

export type AggregateAbhiCallEpisodeDraft = {
  _count: AbhiCallEpisodeDraftCountAggregateOutputType | null
  _avg: AbhiCallEpisodeDraftAvgAggregateOutputType | null
  _sum: AbhiCallEpisodeDraftSumAggregateOutputType | null
  _min: AbhiCallEpisodeDraftMinAggregateOutputType | null
  _max: AbhiCallEpisodeDraftMaxAggregateOutputType | null
}

export type AbhiCallEpisodeDraftAvgAggregateOutputType = {
  episodeAudioSize: number | null
  responseAudioSize: number | null
}

export type AbhiCallEpisodeDraftSumAggregateOutputType = {
  episodeAudioSize: number | null
  responseAudioSize: number | null
}

export type AbhiCallEpisodeDraftMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  status: $Enums.AbhiCallEpisodeDraftStatus | null
  step: $Enums.AbhiCallEpisodeDraftStep | null
  errorMessage: string | null
  episodeAudioKey: string | null
  episodeAudioContentType: string | null
  episodeAudioSize: number | null
  responseAudioKey: string | null
  responseAudioContentType: string | null
  responseAudioSize: number | null
  callerSegmentAudioKey: string | null
  responseSegmentAudioKey: string | null
  transcript: string | null
  title: string | null
  description: string | null
  keywords: string | null
  callId: string | null
}

export type AbhiCallEpisodeDraftMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  status: $Enums.AbhiCallEpisodeDraftStatus | null
  step: $Enums.AbhiCallEpisodeDraftStep | null
  errorMessage: string | null
  episodeAudioKey: string | null
  episodeAudioContentType: string | null
  episodeAudioSize: number | null
  responseAudioKey: string | null
  responseAudioContentType: string | null
  responseAudioSize: number | null
  callerSegmentAudioKey: string | null
  responseSegmentAudioKey: string | null
  transcript: string | null
  title: string | null
  description: string | null
  keywords: string | null
  callId: string | null
}

export type AbhiCallEpisodeDraftCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  status: number
  step: number
  errorMessage: number
  episodeAudioKey: number
  episodeAudioContentType: number
  episodeAudioSize: number
  responseAudioKey: number
  responseAudioContentType: number
  responseAudioSize: number
  callerSegmentAudioKey: number
  responseSegmentAudioKey: number
  transcript: number
  title: number
  description: number
  keywords: number
  callId: number
  _all: number
}


export type AbhiCallEpisodeDraftAvgAggregateInputType = {
  episodeAudioSize?: true
  responseAudioSize?: true
}

export type AbhiCallEpisodeDraftSumAggregateInputType = {
  episodeAudioSize?: true
  responseAudioSize?: true
}

export type AbhiCallEpisodeDraftMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  status?: true
  step?: true
  errorMessage?: true
  episodeAudioKey?: true
  episodeAudioContentType?: true
  episodeAudioSize?: true
  responseAudioKey?: true
  responseAudioContentType?: true
  responseAudioSize?: true
  callerSegmentAudioKey?: true
  responseSegmentAudioKey?: true
  transcript?: true
  title?: true
  description?: true
  keywords?: true
  callId?: true
}

export type AbhiCallEpisodeDraftMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  status?: true
  step?: true
  errorMessage?: true
  episodeAudioKey?: true
  episodeAudioContentType?: true
  episodeAudioSize?: true
  responseAudioKey?: true
  responseAudioContentType?: true
  responseAudioSize?: true
  callerSegmentAudioKey?: true
  responseSegmentAudioKey?: true
  transcript?: true
  title?: true
  description?: true
  keywords?: true
  callId?: true
}

export type AbhiCallEpisodeDraftCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  status?: true
  step?: true
  errorMessage?: true
  episodeAudioKey?: true
  episodeAudioContentType?: true
  episodeAudioSize?: true
  responseAudioKey?: true
  responseAudioContentType?: true
  responseAudioSize?: true
  callerSegmentAudioKey?: true
  responseSegmentAudioKey?: true
  transcript?: true
  title?: true
  description?: true
  keywords?: true
  callId?: true
  _all?: true
}

export type AbhiCallEpisodeDraftAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AbhiCallEpisodeDraft to aggregate.
   */
  where?: Prisma.AbhiCallEpisodeDraftWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AbhiCallEpisodeDrafts to fetch.
   */
  orderBy?: Prisma.AbhiCallEpisodeDraftOrderByWithRelationInput | Prisma.AbhiCallEpisodeDraftOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AbhiCallEpisodeDraftWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AbhiCallEpisodeDrafts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AbhiCallEpisodeDrafts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AbhiCallEpisodeDrafts
  **/
  _count?: true | AbhiCallEpisodeDraftCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AbhiCallEpisodeDraftAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AbhiCallEpisodeDraftSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AbhiCallEpisodeDraftMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AbhiCallEpisodeDraftMaxAggregateInputType
}

export type GetAbhiCallEpisodeDraftAggregateType<T extends AbhiCallEpisodeDraftAggregateArgs> = {
      [P in keyof T & keyof AggregateAbhiCallEpisodeDraft]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAbhiCallEpisodeDraft[P]>
    : Prisma.GetScalarType<T[P], AggregateAbhiCallEpisodeDraft[P]>
}




export type AbhiCallEpisodeDraftGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AbhiCallEpisodeDraftWhereInput
  orderBy?: Prisma.AbhiCallEpisodeDraftOrderByWithAggregationInput | Prisma.AbhiCallEpisodeDraftOrderByWithAggregationInput[]
  by: Prisma.AbhiCallEpisodeDraftScalarFieldEnum[] | Prisma.AbhiCallEpisodeDraftScalarFieldEnum
  having?: Prisma.AbhiCallEpisodeDraftScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AbhiCallEpisodeDraftCountAggregateInputType | true
  _avg?: AbhiCallEpisodeDraftAvgAggregateInputType
  _sum?: AbhiCallEpisodeDraftSumAggregateInputType
  _min?: AbhiCallEpisodeDraftMinAggregateInputType
  _max?: AbhiCallEpisodeDraftMaxAggregateInputType
}

export type AbhiCallEpisodeDraftGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  status: $Enums.AbhiCallEpisodeDraftStatus
  step: $Enums.AbhiCallEpisodeDraftStep
  errorMessage: string | null
  episodeAudioKey: string | null
  episodeAudioContentType: string | null
  episodeAudioSize: number | null
  responseAudioKey: string | null
  responseAudioContentType: string | null
  responseAudioSize: number | null
  callerSegmentAudioKey: string | null
  responseSegmentAudioKey: string | null
  transcript: string | null
  title: string | null
  description: string | null
  keywords: string | null
  callId: string
  _count: AbhiCallEpisodeDraftCountAggregateOutputType | null
  _avg: AbhiCallEpisodeDraftAvgAggregateOutputType | null
  _sum: AbhiCallEpisodeDraftSumAggregateOutputType | null
  _min: AbhiCallEpisodeDraftMinAggregateOutputType | null
  _max: AbhiCallEpisodeDraftMaxAggregateOutputType | null
}

export type GetAbhiCallEpisodeDraftGroupByPayload<T extends AbhiCallEpisodeDraftGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AbhiCallEpisodeDraftGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AbhiCallEpisodeDraftGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AbhiCallEpisodeDraftGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AbhiCallEpisodeDraftGroupByOutputType[P]>
      }
    >
  >



export type AbhiCallEpisodeDraftWhereInput = {
  AND?: Prisma.AbhiCallEpisodeDraftWhereInput | Prisma.AbhiCallEpisodeDraftWhereInput[]
  OR?: Prisma.AbhiCallEpisodeDraftWhereInput[]
  NOT?: Prisma.AbhiCallEpisodeDraftWhereInput | Prisma.AbhiCallEpisodeDraftWhereInput[]
  id?: Prisma.StringFilter<"AbhiCallEpisodeDraft"> | string
  createdAt?: Prisma.DateTimeFilter<"AbhiCallEpisodeDraft"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AbhiCallEpisodeDraft"> | Date | string
  status?: Prisma.EnumAbhiCallEpisodeDraftStatusFilter<"AbhiCallEpisodeDraft"> | $Enums.AbhiCallEpisodeDraftStatus
  step?: Prisma.EnumAbhiCallEpisodeDraftStepFilter<"AbhiCallEpisodeDraft"> | $Enums.AbhiCallEpisodeDraftStep
  errorMessage?: Prisma.StringNullableFilter<"AbhiCallEpisodeDraft"> | string | null
  episodeAudioKey?: Prisma.StringNullableFilter<"AbhiCallEpisodeDraft"> | string | null
  episodeAudioContentType?: Prisma.StringNullableFilter<"AbhiCallEpisodeDraft"> | string | null
  episodeAudioSize?: Prisma.IntNullableFilter<"AbhiCallEpisodeDraft"> | number | null
  responseAudioKey?: Prisma.StringNullableFilter<"AbhiCallEpisodeDraft"> | string | null
  responseAudioContentType?: Prisma.StringNullableFilter<"AbhiCallEpisodeDraft"> | string | null
  responseAudioSize?: Prisma.IntNullableFilter<"AbhiCallEpisodeDraft"> | number | null
  callerSegmentAudioKey?: Prisma.StringNullableFilter<"AbhiCallEpisodeDraft"> | string | null
  responseSegmentAudioKey?: Prisma.StringNullableFilter<"AbhiCallEpisodeDraft"> | string | null
  transcript?: Prisma.StringNullableFilter<"AbhiCallEpisodeDraft"> | string | null
  title?: Prisma.StringNullableFilter<"AbhiCallEpisodeDraft"> | string | null
  description?: Prisma.StringNullableFilter<"AbhiCallEpisodeDraft"> | string | null
  keywords?: Prisma.StringNullableFilter<"AbhiCallEpisodeDraft"> | string | null
  callId?: Prisma.StringFilter<"AbhiCallEpisodeDraft"> | string
  call?: Prisma.XOR<Prisma.CallScalarRelationFilter, Prisma.CallWhereInput>
}

export type AbhiCallEpisodeDraftOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  status?: Prisma.SortOrder
  step?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrderInput | Prisma.SortOrder
  episodeAudioKey?: Prisma.SortOrderInput | Prisma.SortOrder
  episodeAudioContentType?: Prisma.SortOrderInput | Prisma.SortOrder
  episodeAudioSize?: Prisma.SortOrderInput | Prisma.SortOrder
  responseAudioKey?: Prisma.SortOrderInput | Prisma.SortOrder
  responseAudioContentType?: Prisma.SortOrderInput | Prisma.SortOrder
  responseAudioSize?: Prisma.SortOrderInput | Prisma.SortOrder
  callerSegmentAudioKey?: Prisma.SortOrderInput | Prisma.SortOrder
  responseSegmentAudioKey?: Prisma.SortOrderInput | Prisma.SortOrder
  transcript?: Prisma.SortOrderInput | Prisma.SortOrder
  title?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  keywords?: Prisma.SortOrderInput | Prisma.SortOrder
  callId?: Prisma.SortOrder
  call?: Prisma.CallOrderByWithRelationInput
}

export type AbhiCallEpisodeDraftWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  callId?: string
  AND?: Prisma.AbhiCallEpisodeDraftWhereInput | Prisma.AbhiCallEpisodeDraftWhereInput[]
  OR?: Prisma.AbhiCallEpisodeDraftWhereInput[]
  NOT?: Prisma.AbhiCallEpisodeDraftWhereInput | Prisma.AbhiCallEpisodeDraftWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"AbhiCallEpisodeDraft"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AbhiCallEpisodeDraft"> | Date | string
  status?: Prisma.EnumAbhiCallEpisodeDraftStatusFilter<"AbhiCallEpisodeDraft"> | $Enums.AbhiCallEpisodeDraftStatus
  step?: Prisma.EnumAbhiCallEpisodeDraftStepFilter<"AbhiCallEpisodeDraft"> | $Enums.AbhiCallEpisodeDraftStep
  errorMessage?: Prisma.StringNullableFilter<"AbhiCallEpisodeDraft"> | string | null
  episodeAudioKey?: Prisma.StringNullableFilter<"AbhiCallEpisodeDraft"> | string | null
  episodeAudioContentType?: Prisma.StringNullableFilter<"AbhiCallEpisodeDraft"> | string | null
  episodeAudioSize?: Prisma.IntNullableFilter<"AbhiCallEpisodeDraft"> | number | null
  responseAudioKey?: Prisma.StringNullableFilter<"AbhiCallEpisodeDraft"> | string | null
  responseAudioContentType?: Prisma.StringNullableFilter<"AbhiCallEpisodeDraft"> | string | null
  responseAudioSize?: Prisma.IntNullableFilter<"AbhiCallEpisodeDraft"> | number | null
  callerSegmentAudioKey?: Prisma.StringNullableFilter<"AbhiCallEpisodeDraft"> | string | null
  responseSegmentAudioKey?: Prisma.StringNullableFilter<"AbhiCallEpisodeDraft"> | string | null
  transcript?: Prisma.StringNullableFilter<"AbhiCallEpisodeDraft"> | string | null
  title?: Prisma.StringNullableFilter<"AbhiCallEpisodeDraft"> | string | null
  description?: Prisma.StringNullableFilter<"AbhiCallEpisodeDraft"> | string | null
  keywords?: Prisma.StringNullableFilter<"AbhiCallEpisodeDraft"> | string | null
  call?: Prisma.XOR<Prisma.CallScalarRelationFilter, Prisma.CallWhereInput>
}, "id" | "callId">

export type AbhiCallEpisodeDraftOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  status?: Prisma.SortOrder
  step?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrderInput | Prisma.SortOrder
  episodeAudioKey?: Prisma.SortOrderInput | Prisma.SortOrder
  episodeAudioContentType?: Prisma.SortOrderInput | Prisma.SortOrder
  episodeAudioSize?: Prisma.SortOrderInput | Prisma.SortOrder
  responseAudioKey?: Prisma.SortOrderInput | Prisma.SortOrder
  responseAudioContentType?: Prisma.SortOrderInput | Prisma.SortOrder
  responseAudioSize?: Prisma.SortOrderInput | Prisma.SortOrder
  callerSegmentAudioKey?: Prisma.SortOrderInput | Prisma.SortOrder
  responseSegmentAudioKey?: Prisma.SortOrderInput | Prisma.SortOrder
  transcript?: Prisma.SortOrderInput | Prisma.SortOrder
  title?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  keywords?: Prisma.SortOrderInput | Prisma.SortOrder
  callId?: Prisma.SortOrder
  _count?: Prisma.AbhiCallEpisodeDraftCountOrderByAggregateInput
  _avg?: Prisma.AbhiCallEpisodeDraftAvgOrderByAggregateInput
  _max?: Prisma.AbhiCallEpisodeDraftMaxOrderByAggregateInput
  _min?: Prisma.AbhiCallEpisodeDraftMinOrderByAggregateInput
  _sum?: Prisma.AbhiCallEpisodeDraftSumOrderByAggregateInput
}

export type AbhiCallEpisodeDraftScalarWhereWithAggregatesInput = {
  AND?: Prisma.AbhiCallEpisodeDraftScalarWhereWithAggregatesInput | Prisma.AbhiCallEpisodeDraftScalarWhereWithAggregatesInput[]
  OR?: Prisma.AbhiCallEpisodeDraftScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AbhiCallEpisodeDraftScalarWhereWithAggregatesInput | Prisma.AbhiCallEpisodeDraftScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AbhiCallEpisodeDraft"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AbhiCallEpisodeDraft"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AbhiCallEpisodeDraft"> | Date | string
  status?: Prisma.EnumAbhiCallEpisodeDraftStatusWithAggregatesFilter<"AbhiCallEpisodeDraft"> | $Enums.AbhiCallEpisodeDraftStatus
  step?: Prisma.EnumAbhiCallEpisodeDraftStepWithAggregatesFilter<"AbhiCallEpisodeDraft"> | $Enums.AbhiCallEpisodeDraftStep
  errorMessage?: Prisma.StringNullableWithAggregatesFilter<"AbhiCallEpisodeDraft"> | string | null
  episodeAudioKey?: Prisma.StringNullableWithAggregatesFilter<"AbhiCallEpisodeDraft"> | string | null
  episodeAudioContentType?: Prisma.StringNullableWithAggregatesFilter<"AbhiCallEpisodeDraft"> | string | null
  episodeAudioSize?: Prisma.IntNullableWithAggregatesFilter<"AbhiCallEpisodeDraft"> | number | null
  responseAudioKey?: Prisma.StringNullableWithAggregatesFilter<"AbhiCallEpisodeDraft"> | string | null
  responseAudioContentType?: Prisma.StringNullableWithAggregatesFilter<"AbhiCallEpisodeDraft"> | string | null
  responseAudioSize?: Prisma.IntNullableWithAggregatesFilter<"AbhiCallEpisodeDraft"> | number | null
  callerSegmentAudioKey?: Prisma.StringNullableWithAggregatesFilter<"AbhiCallEpisodeDraft"> | string | null
  responseSegmentAudioKey?: Prisma.StringNullableWithAggregatesFilter<"AbhiCallEpisodeDraft"> | string | null
  transcript?: Prisma.StringNullableWithAggregatesFilter<"AbhiCallEpisodeDraft"> | string | null
  title?: Prisma.StringNullableWithAggregatesFilter<"AbhiCallEpisodeDraft"> | string | null
  description?: Prisma.StringNullableWithAggregatesFilter<"AbhiCallEpisodeDraft"> | string | null
  keywords?: Prisma.StringNullableWithAggregatesFilter<"AbhiCallEpisodeDraft"> | string | null
  callId?: Prisma.StringWithAggregatesFilter<"AbhiCallEpisodeDraft"> | string
}

export type AbhiCallEpisodeDraftCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  status?: $Enums.AbhiCallEpisodeDraftStatus
  step?: $Enums.AbhiCallEpisodeDraftStep
  errorMessage?: string | null
  episodeAudioKey?: string | null
  episodeAudioContentType?: string | null
  episodeAudioSize?: number | null
  responseAudioKey?: string | null
  responseAudioContentType?: string | null
  responseAudioSize?: number | null
  callerSegmentAudioKey?: string | null
  responseSegmentAudioKey?: string | null
  transcript?: string | null
  title?: string | null
  description?: string | null
  keywords?: string | null
  call: Prisma.CallCreateNestedOneWithoutEpisodeDraftInput
}

export type AbhiCallEpisodeDraftUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  status?: $Enums.AbhiCallEpisodeDraftStatus
  step?: $Enums.AbhiCallEpisodeDraftStep
  errorMessage?: string | null
  episodeAudioKey?: string | null
  episodeAudioContentType?: string | null
  episodeAudioSize?: number | null
  responseAudioKey?: string | null
  responseAudioContentType?: string | null
  responseAudioSize?: number | null
  callerSegmentAudioKey?: string | null
  responseSegmentAudioKey?: string | null
  transcript?: string | null
  title?: string | null
  description?: string | null
  keywords?: string | null
  callId: string
}

export type AbhiCallEpisodeDraftUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumAbhiCallEpisodeDraftStatusFieldUpdateOperationsInput | $Enums.AbhiCallEpisodeDraftStatus
  step?: Prisma.EnumAbhiCallEpisodeDraftStepFieldUpdateOperationsInput | $Enums.AbhiCallEpisodeDraftStep
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  episodeAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  episodeAudioContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  episodeAudioSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  responseAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  responseAudioContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  responseAudioSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  callerSegmentAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  responseSegmentAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transcript?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  keywords?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  call?: Prisma.CallUpdateOneRequiredWithoutEpisodeDraftNestedInput
}

export type AbhiCallEpisodeDraftUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumAbhiCallEpisodeDraftStatusFieldUpdateOperationsInput | $Enums.AbhiCallEpisodeDraftStatus
  step?: Prisma.EnumAbhiCallEpisodeDraftStepFieldUpdateOperationsInput | $Enums.AbhiCallEpisodeDraftStep
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  episodeAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  episodeAudioContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  episodeAudioSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  responseAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  responseAudioContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  responseAudioSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  callerSegmentAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  responseSegmentAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transcript?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  keywords?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  callId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AbhiCallEpisodeDraftCreateManyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  status?: $Enums.AbhiCallEpisodeDraftStatus
  step?: $Enums.AbhiCallEpisodeDraftStep
  errorMessage?: string | null
  episodeAudioKey?: string | null
  episodeAudioContentType?: string | null
  episodeAudioSize?: number | null
  responseAudioKey?: string | null
  responseAudioContentType?: string | null
  responseAudioSize?: number | null
  callerSegmentAudioKey?: string | null
  responseSegmentAudioKey?: string | null
  transcript?: string | null
  title?: string | null
  description?: string | null
  keywords?: string | null
  callId: string
}

export type AbhiCallEpisodeDraftUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumAbhiCallEpisodeDraftStatusFieldUpdateOperationsInput | $Enums.AbhiCallEpisodeDraftStatus
  step?: Prisma.EnumAbhiCallEpisodeDraftStepFieldUpdateOperationsInput | $Enums.AbhiCallEpisodeDraftStep
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  episodeAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  episodeAudioContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  episodeAudioSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  responseAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  responseAudioContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  responseAudioSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  callerSegmentAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  responseSegmentAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transcript?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  keywords?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AbhiCallEpisodeDraftUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumAbhiCallEpisodeDraftStatusFieldUpdateOperationsInput | $Enums.AbhiCallEpisodeDraftStatus
  step?: Prisma.EnumAbhiCallEpisodeDraftStepFieldUpdateOperationsInput | $Enums.AbhiCallEpisodeDraftStep
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  episodeAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  episodeAudioContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  episodeAudioSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  responseAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  responseAudioContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  responseAudioSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  callerSegmentAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  responseSegmentAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transcript?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  keywords?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  callId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AbhiCallEpisodeDraftNullableScalarRelationFilter = {
  is?: Prisma.AbhiCallEpisodeDraftWhereInput | null
  isNot?: Prisma.AbhiCallEpisodeDraftWhereInput | null
}

export type AbhiCallEpisodeDraftCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  status?: Prisma.SortOrder
  step?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrder
  episodeAudioKey?: Prisma.SortOrder
  episodeAudioContentType?: Prisma.SortOrder
  episodeAudioSize?: Prisma.SortOrder
  responseAudioKey?: Prisma.SortOrder
  responseAudioContentType?: Prisma.SortOrder
  responseAudioSize?: Prisma.SortOrder
  callerSegmentAudioKey?: Prisma.SortOrder
  responseSegmentAudioKey?: Prisma.SortOrder
  transcript?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  keywords?: Prisma.SortOrder
  callId?: Prisma.SortOrder
}

export type AbhiCallEpisodeDraftAvgOrderByAggregateInput = {
  episodeAudioSize?: Prisma.SortOrder
  responseAudioSize?: Prisma.SortOrder
}

export type AbhiCallEpisodeDraftMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  status?: Prisma.SortOrder
  step?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrder
  episodeAudioKey?: Prisma.SortOrder
  episodeAudioContentType?: Prisma.SortOrder
  episodeAudioSize?: Prisma.SortOrder
  responseAudioKey?: Prisma.SortOrder
  responseAudioContentType?: Prisma.SortOrder
  responseAudioSize?: Prisma.SortOrder
  callerSegmentAudioKey?: Prisma.SortOrder
  responseSegmentAudioKey?: Prisma.SortOrder
  transcript?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  keywords?: Prisma.SortOrder
  callId?: Prisma.SortOrder
}

export type AbhiCallEpisodeDraftMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  status?: Prisma.SortOrder
  step?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrder
  episodeAudioKey?: Prisma.SortOrder
  episodeAudioContentType?: Prisma.SortOrder
  episodeAudioSize?: Prisma.SortOrder
  responseAudioKey?: Prisma.SortOrder
  responseAudioContentType?: Prisma.SortOrder
  responseAudioSize?: Prisma.SortOrder
  callerSegmentAudioKey?: Prisma.SortOrder
  responseSegmentAudioKey?: Prisma.SortOrder
  transcript?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  keywords?: Prisma.SortOrder
  callId?: Prisma.SortOrder
}

export type AbhiCallEpisodeDraftSumOrderByAggregateInput = {
  episodeAudioSize?: Prisma.SortOrder
  responseAudioSize?: Prisma.SortOrder
}

export type AbhiCallEpisodeDraftCreateNestedOneWithoutCallInput = {
  create?: Prisma.XOR<Prisma.AbhiCallEpisodeDraftCreateWithoutCallInput, Prisma.AbhiCallEpisodeDraftUncheckedCreateWithoutCallInput>
  connectOrCreate?: Prisma.AbhiCallEpisodeDraftCreateOrConnectWithoutCallInput
  connect?: Prisma.AbhiCallEpisodeDraftWhereUniqueInput
}

export type AbhiCallEpisodeDraftUncheckedCreateNestedOneWithoutCallInput = {
  create?: Prisma.XOR<Prisma.AbhiCallEpisodeDraftCreateWithoutCallInput, Prisma.AbhiCallEpisodeDraftUncheckedCreateWithoutCallInput>
  connectOrCreate?: Prisma.AbhiCallEpisodeDraftCreateOrConnectWithoutCallInput
  connect?: Prisma.AbhiCallEpisodeDraftWhereUniqueInput
}

export type AbhiCallEpisodeDraftUpdateOneWithoutCallNestedInput = {
  create?: Prisma.XOR<Prisma.AbhiCallEpisodeDraftCreateWithoutCallInput, Prisma.AbhiCallEpisodeDraftUncheckedCreateWithoutCallInput>
  connectOrCreate?: Prisma.AbhiCallEpisodeDraftCreateOrConnectWithoutCallInput
  upsert?: Prisma.AbhiCallEpisodeDraftUpsertWithoutCallInput
  disconnect?: Prisma.AbhiCallEpisodeDraftWhereInput | boolean
  delete?: Prisma.AbhiCallEpisodeDraftWhereInput | boolean
  connect?: Prisma.AbhiCallEpisodeDraftWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AbhiCallEpisodeDraftUpdateToOneWithWhereWithoutCallInput, Prisma.AbhiCallEpisodeDraftUpdateWithoutCallInput>, Prisma.AbhiCallEpisodeDraftUncheckedUpdateWithoutCallInput>
}

export type AbhiCallEpisodeDraftUncheckedUpdateOneWithoutCallNestedInput = {
  create?: Prisma.XOR<Prisma.AbhiCallEpisodeDraftCreateWithoutCallInput, Prisma.AbhiCallEpisodeDraftUncheckedCreateWithoutCallInput>
  connectOrCreate?: Prisma.AbhiCallEpisodeDraftCreateOrConnectWithoutCallInput
  upsert?: Prisma.AbhiCallEpisodeDraftUpsertWithoutCallInput
  disconnect?: Prisma.AbhiCallEpisodeDraftWhereInput | boolean
  delete?: Prisma.AbhiCallEpisodeDraftWhereInput | boolean
  connect?: Prisma.AbhiCallEpisodeDraftWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AbhiCallEpisodeDraftUpdateToOneWithWhereWithoutCallInput, Prisma.AbhiCallEpisodeDraftUpdateWithoutCallInput>, Prisma.AbhiCallEpisodeDraftUncheckedUpdateWithoutCallInput>
}

export type EnumAbhiCallEpisodeDraftStatusFieldUpdateOperationsInput = {
  set?: $Enums.AbhiCallEpisodeDraftStatus
}

export type EnumAbhiCallEpisodeDraftStepFieldUpdateOperationsInput = {
  set?: $Enums.AbhiCallEpisodeDraftStep
}

export type AbhiCallEpisodeDraftCreateWithoutCallInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  status?: $Enums.AbhiCallEpisodeDraftStatus
  step?: $Enums.AbhiCallEpisodeDraftStep
  errorMessage?: string | null
  episodeAudioKey?: string | null
  episodeAudioContentType?: string | null
  episodeAudioSize?: number | null
  responseAudioKey?: string | null
  responseAudioContentType?: string | null
  responseAudioSize?: number | null
  callerSegmentAudioKey?: string | null
  responseSegmentAudioKey?: string | null
  transcript?: string | null
  title?: string | null
  description?: string | null
  keywords?: string | null
}

export type AbhiCallEpisodeDraftUncheckedCreateWithoutCallInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  status?: $Enums.AbhiCallEpisodeDraftStatus
  step?: $Enums.AbhiCallEpisodeDraftStep
  errorMessage?: string | null
  episodeAudioKey?: string | null
  episodeAudioContentType?: string | null
  episodeAudioSize?: number | null
  responseAudioKey?: string | null
  responseAudioContentType?: string | null
  responseAudioSize?: number | null
  callerSegmentAudioKey?: string | null
  responseSegmentAudioKey?: string | null
  transcript?: string | null
  title?: string | null
  description?: string | null
  keywords?: string | null
}

export type AbhiCallEpisodeDraftCreateOrConnectWithoutCallInput = {
  where: Prisma.AbhiCallEpisodeDraftWhereUniqueInput
  create: Prisma.XOR<Prisma.AbhiCallEpisodeDraftCreateWithoutCallInput, Prisma.AbhiCallEpisodeDraftUncheckedCreateWithoutCallInput>
}

export type AbhiCallEpisodeDraftUpsertWithoutCallInput = {
  update: Prisma.XOR<Prisma.AbhiCallEpisodeDraftUpdateWithoutCallInput, Prisma.AbhiCallEpisodeDraftUncheckedUpdateWithoutCallInput>
  create: Prisma.XOR<Prisma.AbhiCallEpisodeDraftCreateWithoutCallInput, Prisma.AbhiCallEpisodeDraftUncheckedCreateWithoutCallInput>
  where?: Prisma.AbhiCallEpisodeDraftWhereInput
}

export type AbhiCallEpisodeDraftUpdateToOneWithWhereWithoutCallInput = {
  where?: Prisma.AbhiCallEpisodeDraftWhereInput
  data: Prisma.XOR<Prisma.AbhiCallEpisodeDraftUpdateWithoutCallInput, Prisma.AbhiCallEpisodeDraftUncheckedUpdateWithoutCallInput>
}

export type AbhiCallEpisodeDraftUpdateWithoutCallInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumAbhiCallEpisodeDraftStatusFieldUpdateOperationsInput | $Enums.AbhiCallEpisodeDraftStatus
  step?: Prisma.EnumAbhiCallEpisodeDraftStepFieldUpdateOperationsInput | $Enums.AbhiCallEpisodeDraftStep
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  episodeAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  episodeAudioContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  episodeAudioSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  responseAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  responseAudioContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  responseAudioSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  callerSegmentAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  responseSegmentAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transcript?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  keywords?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AbhiCallEpisodeDraftUncheckedUpdateWithoutCallInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.EnumAbhiCallEpisodeDraftStatusFieldUpdateOperationsInput | $Enums.AbhiCallEpisodeDraftStatus
  step?: Prisma.EnumAbhiCallEpisodeDraftStepFieldUpdateOperationsInput | $Enums.AbhiCallEpisodeDraftStep
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  episodeAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  episodeAudioContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  episodeAudioSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  responseAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  responseAudioContentType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  responseAudioSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  callerSegmentAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  responseSegmentAudioKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transcript?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  title?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  keywords?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type AbhiCallEpisodeDraftSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  status?: boolean
  step?: boolean
  errorMessage?: boolean
  episodeAudioKey?: boolean
  episodeAudioContentType?: boolean
  episodeAudioSize?: boolean
  responseAudioKey?: boolean
  responseAudioContentType?: boolean
  responseAudioSize?: boolean
  callerSegmentAudioKey?: boolean
  responseSegmentAudioKey?: boolean
  transcript?: boolean
  title?: boolean
  description?: boolean
  keywords?: boolean
  callId?: boolean
  call?: boolean | Prisma.CallDefaultArgs<ExtArgs>
}, ExtArgs["result"]["abhiCallEpisodeDraft"]>

export type AbhiCallEpisodeDraftSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  status?: boolean
  step?: boolean
  errorMessage?: boolean
  episodeAudioKey?: boolean
  episodeAudioContentType?: boolean
  episodeAudioSize?: boolean
  responseAudioKey?: boolean
  responseAudioContentType?: boolean
  responseAudioSize?: boolean
  callerSegmentAudioKey?: boolean
  responseSegmentAudioKey?: boolean
  transcript?: boolean
  title?: boolean
  description?: boolean
  keywords?: boolean
  callId?: boolean
  call?: boolean | Prisma.CallDefaultArgs<ExtArgs>
}, ExtArgs["result"]["abhiCallEpisodeDraft"]>

export type AbhiCallEpisodeDraftSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  status?: boolean
  step?: boolean
  errorMessage?: boolean
  episodeAudioKey?: boolean
  episodeAudioContentType?: boolean
  episodeAudioSize?: boolean
  responseAudioKey?: boolean
  responseAudioContentType?: boolean
  responseAudioSize?: boolean
  callerSegmentAudioKey?: boolean
  responseSegmentAudioKey?: boolean
  transcript?: boolean
  title?: boolean
  description?: boolean
  keywords?: boolean
  callId?: boolean
  call?: boolean | Prisma.CallDefaultArgs<ExtArgs>
}, ExtArgs["result"]["abhiCallEpisodeDraft"]>

export type AbhiCallEpisodeDraftSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  status?: boolean
  step?: boolean
  errorMessage?: boolean
  episodeAudioKey?: boolean
  episodeAudioContentType?: boolean
  episodeAudioSize?: boolean
  responseAudioKey?: boolean
  responseAudioContentType?: boolean
  responseAudioSize?: boolean
  callerSegmentAudioKey?: boolean
  responseSegmentAudioKey?: boolean
  transcript?: boolean
  title?: boolean
  description?: boolean
  keywords?: boolean
  callId?: boolean
}

export type AbhiCallEpisodeDraftOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "status" | "step" | "errorMessage" | "episodeAudioKey" | "episodeAudioContentType" | "episodeAudioSize" | "responseAudioKey" | "responseAudioContentType" | "responseAudioSize" | "callerSegmentAudioKey" | "responseSegmentAudioKey" | "transcript" | "title" | "description" | "keywords" | "callId", ExtArgs["result"]["abhiCallEpisodeDraft"]>
export type AbhiCallEpisodeDraftInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  call?: boolean | Prisma.CallDefaultArgs<ExtArgs>
}
export type AbhiCallEpisodeDraftIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  call?: boolean | Prisma.CallDefaultArgs<ExtArgs>
}
export type AbhiCallEpisodeDraftIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  call?: boolean | Prisma.CallDefaultArgs<ExtArgs>
}

export type $AbhiCallEpisodeDraftPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AbhiCallEpisodeDraft"
  objects: {
    call: Prisma.$CallPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    status: $Enums.AbhiCallEpisodeDraftStatus
    step: $Enums.AbhiCallEpisodeDraftStep
    errorMessage: string | null
    episodeAudioKey: string | null
    episodeAudioContentType: string | null
    episodeAudioSize: number | null
    responseAudioKey: string | null
    responseAudioContentType: string | null
    responseAudioSize: number | null
    callerSegmentAudioKey: string | null
    responseSegmentAudioKey: string | null
    transcript: string | null
    title: string | null
    description: string | null
    keywords: string | null
    callId: string
  }, ExtArgs["result"]["abhiCallEpisodeDraft"]>
  composites: {}
}

export type AbhiCallEpisodeDraftGetPayload<S extends boolean | null | undefined | AbhiCallEpisodeDraftDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AbhiCallEpisodeDraftPayload, S>

export type AbhiCallEpisodeDraftCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AbhiCallEpisodeDraftFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AbhiCallEpisodeDraftCountAggregateInputType | true
  }

export interface AbhiCallEpisodeDraftDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AbhiCallEpisodeDraft'], meta: { name: 'AbhiCallEpisodeDraft' } }
  /**
   * Find zero or one AbhiCallEpisodeDraft that matches the filter.
   * @param {AbhiCallEpisodeDraftFindUniqueArgs} args - Arguments to find a AbhiCallEpisodeDraft
   * @example
   * // Get one AbhiCallEpisodeDraft
   * const abhiCallEpisodeDraft = await prisma.abhiCallEpisodeDraft.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AbhiCallEpisodeDraftFindUniqueArgs>(args: Prisma.SelectSubset<T, AbhiCallEpisodeDraftFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AbhiCallEpisodeDraftClient<runtime.Types.Result.GetResult<Prisma.$AbhiCallEpisodeDraftPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AbhiCallEpisodeDraft that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AbhiCallEpisodeDraftFindUniqueOrThrowArgs} args - Arguments to find a AbhiCallEpisodeDraft
   * @example
   * // Get one AbhiCallEpisodeDraft
   * const abhiCallEpisodeDraft = await prisma.abhiCallEpisodeDraft.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AbhiCallEpisodeDraftFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AbhiCallEpisodeDraftFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AbhiCallEpisodeDraftClient<runtime.Types.Result.GetResult<Prisma.$AbhiCallEpisodeDraftPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AbhiCallEpisodeDraft that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbhiCallEpisodeDraftFindFirstArgs} args - Arguments to find a AbhiCallEpisodeDraft
   * @example
   * // Get one AbhiCallEpisodeDraft
   * const abhiCallEpisodeDraft = await prisma.abhiCallEpisodeDraft.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AbhiCallEpisodeDraftFindFirstArgs>(args?: Prisma.SelectSubset<T, AbhiCallEpisodeDraftFindFirstArgs<ExtArgs>>): Prisma.Prisma__AbhiCallEpisodeDraftClient<runtime.Types.Result.GetResult<Prisma.$AbhiCallEpisodeDraftPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AbhiCallEpisodeDraft that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbhiCallEpisodeDraftFindFirstOrThrowArgs} args - Arguments to find a AbhiCallEpisodeDraft
   * @example
   * // Get one AbhiCallEpisodeDraft
   * const abhiCallEpisodeDraft = await prisma.abhiCallEpisodeDraft.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AbhiCallEpisodeDraftFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AbhiCallEpisodeDraftFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AbhiCallEpisodeDraftClient<runtime.Types.Result.GetResult<Prisma.$AbhiCallEpisodeDraftPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AbhiCallEpisodeDrafts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbhiCallEpisodeDraftFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AbhiCallEpisodeDrafts
   * const abhiCallEpisodeDrafts = await prisma.abhiCallEpisodeDraft.findMany()
   * 
   * // Get first 10 AbhiCallEpisodeDrafts
   * const abhiCallEpisodeDrafts = await prisma.abhiCallEpisodeDraft.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const abhiCallEpisodeDraftWithIdOnly = await prisma.abhiCallEpisodeDraft.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AbhiCallEpisodeDraftFindManyArgs>(args?: Prisma.SelectSubset<T, AbhiCallEpisodeDraftFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AbhiCallEpisodeDraftPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AbhiCallEpisodeDraft.
   * @param {AbhiCallEpisodeDraftCreateArgs} args - Arguments to create a AbhiCallEpisodeDraft.
   * @example
   * // Create one AbhiCallEpisodeDraft
   * const AbhiCallEpisodeDraft = await prisma.abhiCallEpisodeDraft.create({
   *   data: {
   *     // ... data to create a AbhiCallEpisodeDraft
   *   }
   * })
   * 
   */
  create<T extends AbhiCallEpisodeDraftCreateArgs>(args: Prisma.SelectSubset<T, AbhiCallEpisodeDraftCreateArgs<ExtArgs>>): Prisma.Prisma__AbhiCallEpisodeDraftClient<runtime.Types.Result.GetResult<Prisma.$AbhiCallEpisodeDraftPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AbhiCallEpisodeDrafts.
   * @param {AbhiCallEpisodeDraftCreateManyArgs} args - Arguments to create many AbhiCallEpisodeDrafts.
   * @example
   * // Create many AbhiCallEpisodeDrafts
   * const abhiCallEpisodeDraft = await prisma.abhiCallEpisodeDraft.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AbhiCallEpisodeDraftCreateManyArgs>(args?: Prisma.SelectSubset<T, AbhiCallEpisodeDraftCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AbhiCallEpisodeDrafts and returns the data saved in the database.
   * @param {AbhiCallEpisodeDraftCreateManyAndReturnArgs} args - Arguments to create many AbhiCallEpisodeDrafts.
   * @example
   * // Create many AbhiCallEpisodeDrafts
   * const abhiCallEpisodeDraft = await prisma.abhiCallEpisodeDraft.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AbhiCallEpisodeDrafts and only return the `id`
   * const abhiCallEpisodeDraftWithIdOnly = await prisma.abhiCallEpisodeDraft.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AbhiCallEpisodeDraftCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AbhiCallEpisodeDraftCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AbhiCallEpisodeDraftPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AbhiCallEpisodeDraft.
   * @param {AbhiCallEpisodeDraftDeleteArgs} args - Arguments to delete one AbhiCallEpisodeDraft.
   * @example
   * // Delete one AbhiCallEpisodeDraft
   * const AbhiCallEpisodeDraft = await prisma.abhiCallEpisodeDraft.delete({
   *   where: {
   *     // ... filter to delete one AbhiCallEpisodeDraft
   *   }
   * })
   * 
   */
  delete<T extends AbhiCallEpisodeDraftDeleteArgs>(args: Prisma.SelectSubset<T, AbhiCallEpisodeDraftDeleteArgs<ExtArgs>>): Prisma.Prisma__AbhiCallEpisodeDraftClient<runtime.Types.Result.GetResult<Prisma.$AbhiCallEpisodeDraftPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AbhiCallEpisodeDraft.
   * @param {AbhiCallEpisodeDraftUpdateArgs} args - Arguments to update one AbhiCallEpisodeDraft.
   * @example
   * // Update one AbhiCallEpisodeDraft
   * const abhiCallEpisodeDraft = await prisma.abhiCallEpisodeDraft.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AbhiCallEpisodeDraftUpdateArgs>(args: Prisma.SelectSubset<T, AbhiCallEpisodeDraftUpdateArgs<ExtArgs>>): Prisma.Prisma__AbhiCallEpisodeDraftClient<runtime.Types.Result.GetResult<Prisma.$AbhiCallEpisodeDraftPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AbhiCallEpisodeDrafts.
   * @param {AbhiCallEpisodeDraftDeleteManyArgs} args - Arguments to filter AbhiCallEpisodeDrafts to delete.
   * @example
   * // Delete a few AbhiCallEpisodeDrafts
   * const { count } = await prisma.abhiCallEpisodeDraft.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AbhiCallEpisodeDraftDeleteManyArgs>(args?: Prisma.SelectSubset<T, AbhiCallEpisodeDraftDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AbhiCallEpisodeDrafts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbhiCallEpisodeDraftUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AbhiCallEpisodeDrafts
   * const abhiCallEpisodeDraft = await prisma.abhiCallEpisodeDraft.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AbhiCallEpisodeDraftUpdateManyArgs>(args: Prisma.SelectSubset<T, AbhiCallEpisodeDraftUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AbhiCallEpisodeDrafts and returns the data updated in the database.
   * @param {AbhiCallEpisodeDraftUpdateManyAndReturnArgs} args - Arguments to update many AbhiCallEpisodeDrafts.
   * @example
   * // Update many AbhiCallEpisodeDrafts
   * const abhiCallEpisodeDraft = await prisma.abhiCallEpisodeDraft.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AbhiCallEpisodeDrafts and only return the `id`
   * const abhiCallEpisodeDraftWithIdOnly = await prisma.abhiCallEpisodeDraft.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AbhiCallEpisodeDraftUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AbhiCallEpisodeDraftUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AbhiCallEpisodeDraftPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AbhiCallEpisodeDraft.
   * @param {AbhiCallEpisodeDraftUpsertArgs} args - Arguments to update or create a AbhiCallEpisodeDraft.
   * @example
   * // Update or create a AbhiCallEpisodeDraft
   * const abhiCallEpisodeDraft = await prisma.abhiCallEpisodeDraft.upsert({
   *   create: {
   *     // ... data to create a AbhiCallEpisodeDraft
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AbhiCallEpisodeDraft we want to update
   *   }
   * })
   */
  upsert<T extends AbhiCallEpisodeDraftUpsertArgs>(args: Prisma.SelectSubset<T, AbhiCallEpisodeDraftUpsertArgs<ExtArgs>>): Prisma.Prisma__AbhiCallEpisodeDraftClient<runtime.Types.Result.GetResult<Prisma.$AbhiCallEpisodeDraftPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AbhiCallEpisodeDrafts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbhiCallEpisodeDraftCountArgs} args - Arguments to filter AbhiCallEpisodeDrafts to count.
   * @example
   * // Count the number of AbhiCallEpisodeDrafts
   * const count = await prisma.abhiCallEpisodeDraft.count({
   *   where: {
   *     // ... the filter for the AbhiCallEpisodeDrafts we want to count
   *   }
   * })
  **/
  count<T extends AbhiCallEpisodeDraftCountArgs>(
    args?: Prisma.Subset<T, AbhiCallEpisodeDraftCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AbhiCallEpisodeDraftCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AbhiCallEpisodeDraft.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbhiCallEpisodeDraftAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AbhiCallEpisodeDraftAggregateArgs>(args: Prisma.Subset<T, AbhiCallEpisodeDraftAggregateArgs>): Prisma.PrismaPromise<GetAbhiCallEpisodeDraftAggregateType<T>>

  /**
   * Group by AbhiCallEpisodeDraft.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbhiCallEpisodeDraftGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AbhiCallEpisodeDraftGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AbhiCallEpisodeDraftGroupByArgs['orderBy'] }
      : { orderBy?: AbhiCallEpisodeDraftGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AbhiCallEpisodeDraftGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAbhiCallEpisodeDraftGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AbhiCallEpisodeDraft model
 */
readonly fields: AbhiCallEpisodeDraftFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AbhiCallEpisodeDraft.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AbhiCallEpisodeDraftClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  call<T extends Prisma.CallDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CallDefaultArgs<ExtArgs>>): Prisma.Prisma__CallClient<runtime.Types.Result.GetResult<Prisma.$CallPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AbhiCallEpisodeDraft model
 */
export interface AbhiCallEpisodeDraftFieldRefs {
  readonly id: Prisma.FieldRef<"AbhiCallEpisodeDraft", 'String'>
  readonly createdAt: Prisma.FieldRef<"AbhiCallEpisodeDraft", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AbhiCallEpisodeDraft", 'DateTime'>
  readonly status: Prisma.FieldRef<"AbhiCallEpisodeDraft", 'AbhiCallEpisodeDraftStatus'>
  readonly step: Prisma.FieldRef<"AbhiCallEpisodeDraft", 'AbhiCallEpisodeDraftStep'>
  readonly errorMessage: Prisma.FieldRef<"AbhiCallEpisodeDraft", 'String'>
  readonly episodeAudioKey: Prisma.FieldRef<"AbhiCallEpisodeDraft", 'String'>
  readonly episodeAudioContentType: Prisma.FieldRef<"AbhiCallEpisodeDraft", 'String'>
  readonly episodeAudioSize: Prisma.FieldRef<"AbhiCallEpisodeDraft", 'Int'>
  readonly responseAudioKey: Prisma.FieldRef<"AbhiCallEpisodeDraft", 'String'>
  readonly responseAudioContentType: Prisma.FieldRef<"AbhiCallEpisodeDraft", 'String'>
  readonly responseAudioSize: Prisma.FieldRef<"AbhiCallEpisodeDraft", 'Int'>
  readonly callerSegmentAudioKey: Prisma.FieldRef<"AbhiCallEpisodeDraft", 'String'>
  readonly responseSegmentAudioKey: Prisma.FieldRef<"AbhiCallEpisodeDraft", 'String'>
  readonly transcript: Prisma.FieldRef<"AbhiCallEpisodeDraft", 'String'>
  readonly title: Prisma.FieldRef<"AbhiCallEpisodeDraft", 'String'>
  readonly description: Prisma.FieldRef<"AbhiCallEpisodeDraft", 'String'>
  readonly keywords: Prisma.FieldRef<"AbhiCallEpisodeDraft", 'String'>
  readonly callId: Prisma.FieldRef<"AbhiCallEpisodeDraft", 'String'>
}
    

// Custom InputTypes
/**
 * AbhiCallEpisodeDraft findUnique
 */
export type AbhiCallEpisodeDraftFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AbhiCallEpisodeDraft
   */
  select?: Prisma.AbhiCallEpisodeDraftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AbhiCallEpisodeDraft
   */
  omit?: Prisma.AbhiCallEpisodeDraftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbhiCallEpisodeDraftInclude<ExtArgs> | null
  /**
   * Filter, which AbhiCallEpisodeDraft to fetch.
   */
  where: Prisma.AbhiCallEpisodeDraftWhereUniqueInput
}

/**
 * AbhiCallEpisodeDraft findUniqueOrThrow
 */
export type AbhiCallEpisodeDraftFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AbhiCallEpisodeDraft
   */
  select?: Prisma.AbhiCallEpisodeDraftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AbhiCallEpisodeDraft
   */
  omit?: Prisma.AbhiCallEpisodeDraftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbhiCallEpisodeDraftInclude<ExtArgs> | null
  /**
   * Filter, which AbhiCallEpisodeDraft to fetch.
   */
  where: Prisma.AbhiCallEpisodeDraftWhereUniqueInput
}

/**
 * AbhiCallEpisodeDraft findFirst
 */
export type AbhiCallEpisodeDraftFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AbhiCallEpisodeDraft
   */
  select?: Prisma.AbhiCallEpisodeDraftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AbhiCallEpisodeDraft
   */
  omit?: Prisma.AbhiCallEpisodeDraftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbhiCallEpisodeDraftInclude<ExtArgs> | null
  /**
   * Filter, which AbhiCallEpisodeDraft to fetch.
   */
  where?: Prisma.AbhiCallEpisodeDraftWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AbhiCallEpisodeDrafts to fetch.
   */
  orderBy?: Prisma.AbhiCallEpisodeDraftOrderByWithRelationInput | Prisma.AbhiCallEpisodeDraftOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AbhiCallEpisodeDrafts.
   */
  cursor?: Prisma.AbhiCallEpisodeDraftWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AbhiCallEpisodeDrafts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AbhiCallEpisodeDrafts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AbhiCallEpisodeDrafts.
   */
  distinct?: Prisma.AbhiCallEpisodeDraftScalarFieldEnum | Prisma.AbhiCallEpisodeDraftScalarFieldEnum[]
}

/**
 * AbhiCallEpisodeDraft findFirstOrThrow
 */
export type AbhiCallEpisodeDraftFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AbhiCallEpisodeDraft
   */
  select?: Prisma.AbhiCallEpisodeDraftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AbhiCallEpisodeDraft
   */
  omit?: Prisma.AbhiCallEpisodeDraftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbhiCallEpisodeDraftInclude<ExtArgs> | null
  /**
   * Filter, which AbhiCallEpisodeDraft to fetch.
   */
  where?: Prisma.AbhiCallEpisodeDraftWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AbhiCallEpisodeDrafts to fetch.
   */
  orderBy?: Prisma.AbhiCallEpisodeDraftOrderByWithRelationInput | Prisma.AbhiCallEpisodeDraftOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AbhiCallEpisodeDrafts.
   */
  cursor?: Prisma.AbhiCallEpisodeDraftWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AbhiCallEpisodeDrafts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AbhiCallEpisodeDrafts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AbhiCallEpisodeDrafts.
   */
  distinct?: Prisma.AbhiCallEpisodeDraftScalarFieldEnum | Prisma.AbhiCallEpisodeDraftScalarFieldEnum[]
}

/**
 * AbhiCallEpisodeDraft findMany
 */
export type AbhiCallEpisodeDraftFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AbhiCallEpisodeDraft
   */
  select?: Prisma.AbhiCallEpisodeDraftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AbhiCallEpisodeDraft
   */
  omit?: Prisma.AbhiCallEpisodeDraftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbhiCallEpisodeDraftInclude<ExtArgs> | null
  /**
   * Filter, which AbhiCallEpisodeDrafts to fetch.
   */
  where?: Prisma.AbhiCallEpisodeDraftWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AbhiCallEpisodeDrafts to fetch.
   */
  orderBy?: Prisma.AbhiCallEpisodeDraftOrderByWithRelationInput | Prisma.AbhiCallEpisodeDraftOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AbhiCallEpisodeDrafts.
   */
  cursor?: Prisma.AbhiCallEpisodeDraftWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AbhiCallEpisodeDrafts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AbhiCallEpisodeDrafts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AbhiCallEpisodeDrafts.
   */
  distinct?: Prisma.AbhiCallEpisodeDraftScalarFieldEnum | Prisma.AbhiCallEpisodeDraftScalarFieldEnum[]
}

/**
 * AbhiCallEpisodeDraft create
 */
export type AbhiCallEpisodeDraftCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AbhiCallEpisodeDraft
   */
  select?: Prisma.AbhiCallEpisodeDraftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AbhiCallEpisodeDraft
   */
  omit?: Prisma.AbhiCallEpisodeDraftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbhiCallEpisodeDraftInclude<ExtArgs> | null
  /**
   * The data needed to create a AbhiCallEpisodeDraft.
   */
  data: Prisma.XOR<Prisma.AbhiCallEpisodeDraftCreateInput, Prisma.AbhiCallEpisodeDraftUncheckedCreateInput>
}

/**
 * AbhiCallEpisodeDraft createMany
 */
export type AbhiCallEpisodeDraftCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AbhiCallEpisodeDrafts.
   */
  data: Prisma.AbhiCallEpisodeDraftCreateManyInput | Prisma.AbhiCallEpisodeDraftCreateManyInput[]
}

/**
 * AbhiCallEpisodeDraft createManyAndReturn
 */
export type AbhiCallEpisodeDraftCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AbhiCallEpisodeDraft
   */
  select?: Prisma.AbhiCallEpisodeDraftSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AbhiCallEpisodeDraft
   */
  omit?: Prisma.AbhiCallEpisodeDraftOmit<ExtArgs> | null
  /**
   * The data used to create many AbhiCallEpisodeDrafts.
   */
  data: Prisma.AbhiCallEpisodeDraftCreateManyInput | Prisma.AbhiCallEpisodeDraftCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbhiCallEpisodeDraftIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AbhiCallEpisodeDraft update
 */
export type AbhiCallEpisodeDraftUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AbhiCallEpisodeDraft
   */
  select?: Prisma.AbhiCallEpisodeDraftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AbhiCallEpisodeDraft
   */
  omit?: Prisma.AbhiCallEpisodeDraftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbhiCallEpisodeDraftInclude<ExtArgs> | null
  /**
   * The data needed to update a AbhiCallEpisodeDraft.
   */
  data: Prisma.XOR<Prisma.AbhiCallEpisodeDraftUpdateInput, Prisma.AbhiCallEpisodeDraftUncheckedUpdateInput>
  /**
   * Choose, which AbhiCallEpisodeDraft to update.
   */
  where: Prisma.AbhiCallEpisodeDraftWhereUniqueInput
}

/**
 * AbhiCallEpisodeDraft updateMany
 */
export type AbhiCallEpisodeDraftUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AbhiCallEpisodeDrafts.
   */
  data: Prisma.XOR<Prisma.AbhiCallEpisodeDraftUpdateManyMutationInput, Prisma.AbhiCallEpisodeDraftUncheckedUpdateManyInput>
  /**
   * Filter which AbhiCallEpisodeDrafts to update
   */
  where?: Prisma.AbhiCallEpisodeDraftWhereInput
  /**
   * Limit how many AbhiCallEpisodeDrafts to update.
   */
  limit?: number
}

/**
 * AbhiCallEpisodeDraft updateManyAndReturn
 */
export type AbhiCallEpisodeDraftUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AbhiCallEpisodeDraft
   */
  select?: Prisma.AbhiCallEpisodeDraftSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AbhiCallEpisodeDraft
   */
  omit?: Prisma.AbhiCallEpisodeDraftOmit<ExtArgs> | null
  /**
   * The data used to update AbhiCallEpisodeDrafts.
   */
  data: Prisma.XOR<Prisma.AbhiCallEpisodeDraftUpdateManyMutationInput, Prisma.AbhiCallEpisodeDraftUncheckedUpdateManyInput>
  /**
   * Filter which AbhiCallEpisodeDrafts to update
   */
  where?: Prisma.AbhiCallEpisodeDraftWhereInput
  /**
   * Limit how many AbhiCallEpisodeDrafts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbhiCallEpisodeDraftIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AbhiCallEpisodeDraft upsert
 */
export type AbhiCallEpisodeDraftUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AbhiCallEpisodeDraft
   */
  select?: Prisma.AbhiCallEpisodeDraftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AbhiCallEpisodeDraft
   */
  omit?: Prisma.AbhiCallEpisodeDraftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbhiCallEpisodeDraftInclude<ExtArgs> | null
  /**
   * The filter to search for the AbhiCallEpisodeDraft to update in case it exists.
   */
  where: Prisma.AbhiCallEpisodeDraftWhereUniqueInput
  /**
   * In case the AbhiCallEpisodeDraft found by the `where` argument doesn't exist, create a new AbhiCallEpisodeDraft with this data.
   */
  create: Prisma.XOR<Prisma.AbhiCallEpisodeDraftCreateInput, Prisma.AbhiCallEpisodeDraftUncheckedCreateInput>
  /**
   * In case the AbhiCallEpisodeDraft was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AbhiCallEpisodeDraftUpdateInput, Prisma.AbhiCallEpisodeDraftUncheckedUpdateInput>
}

/**
 * AbhiCallEpisodeDraft delete
 */
export type AbhiCallEpisodeDraftDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AbhiCallEpisodeDraft
   */
  select?: Prisma.AbhiCallEpisodeDraftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AbhiCallEpisodeDraft
   */
  omit?: Prisma.AbhiCallEpisodeDraftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbhiCallEpisodeDraftInclude<ExtArgs> | null
  /**
   * Filter which AbhiCallEpisodeDraft to delete.
   */
  where: Prisma.AbhiCallEpisodeDraftWhereUniqueInput
}

/**
 * AbhiCallEpisodeDraft deleteMany
 */
export type AbhiCallEpisodeDraftDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AbhiCallEpisodeDrafts to delete
   */
  where?: Prisma.AbhiCallEpisodeDraftWhereInput
  /**
   * Limit how many AbhiCallEpisodeDrafts to delete.
   */
  limit?: number
}

/**
 * AbhiCallEpisodeDraft without action
 */
export type AbhiCallEpisodeDraftDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AbhiCallEpisodeDraft
   */
  select?: Prisma.AbhiCallEpisodeDraftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AbhiCallEpisodeDraft
   */
  omit?: Prisma.AbhiCallEpisodeDraftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbhiCallEpisodeDraftInclude<ExtArgs> | null
}
