
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AbhiCallCallerEpisode` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AbhiCallCallerEpisode
 * 
 */
export type AbhiCallCallerEpisodeModel = runtime.Types.Result.DefaultSelection<Prisma.$AbhiCallCallerEpisodePayload>

export type AggregateAbhiCallCallerEpisode = {
  _count: AbhiCallCallerEpisodeCountAggregateOutputType | null
  _min: AbhiCallCallerEpisodeMinAggregateOutputType | null
  _max: AbhiCallCallerEpisodeMaxAggregateOutputType | null
}

export type AbhiCallCallerEpisodeMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  userId: string | null
  callTitle: string | null
  callNotes: string | null
  isAnonymous: boolean | null
  transistorEpisodeId: string | null
}

export type AbhiCallCallerEpisodeMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  userId: string | null
  callTitle: string | null
  callNotes: string | null
  isAnonymous: boolean | null
  transistorEpisodeId: string | null
}

export type AbhiCallCallerEpisodeCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  userId: number
  callTitle: number
  callNotes: number
  isAnonymous: number
  transistorEpisodeId: number
  _all: number
}


export type AbhiCallCallerEpisodeMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
  callTitle?: true
  callNotes?: true
  isAnonymous?: true
  transistorEpisodeId?: true
}

export type AbhiCallCallerEpisodeMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
  callTitle?: true
  callNotes?: true
  isAnonymous?: true
  transistorEpisodeId?: true
}

export type AbhiCallCallerEpisodeCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
  callTitle?: true
  callNotes?: true
  isAnonymous?: true
  transistorEpisodeId?: true
  _all?: true
}

export type AbhiCallCallerEpisodeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AbhiCallCallerEpisode to aggregate.
   */
  where?: Prisma.AbhiCallCallerEpisodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AbhiCallCallerEpisodes to fetch.
   */
  orderBy?: Prisma.AbhiCallCallerEpisodeOrderByWithRelationInput | Prisma.AbhiCallCallerEpisodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AbhiCallCallerEpisodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AbhiCallCallerEpisodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AbhiCallCallerEpisodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AbhiCallCallerEpisodes
  **/
  _count?: true | AbhiCallCallerEpisodeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AbhiCallCallerEpisodeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AbhiCallCallerEpisodeMaxAggregateInputType
}

export type GetAbhiCallCallerEpisodeAggregateType<T extends AbhiCallCallerEpisodeAggregateArgs> = {
      [P in keyof T & keyof AggregateAbhiCallCallerEpisode]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAbhiCallCallerEpisode[P]>
    : Prisma.GetScalarType<T[P], AggregateAbhiCallCallerEpisode[P]>
}




export type AbhiCallCallerEpisodeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AbhiCallCallerEpisodeWhereInput
  orderBy?: Prisma.AbhiCallCallerEpisodeOrderByWithAggregationInput | Prisma.AbhiCallCallerEpisodeOrderByWithAggregationInput[]
  by: Prisma.AbhiCallCallerEpisodeScalarFieldEnum[] | Prisma.AbhiCallCallerEpisodeScalarFieldEnum
  having?: Prisma.AbhiCallCallerEpisodeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AbhiCallCallerEpisodeCountAggregateInputType | true
  _min?: AbhiCallCallerEpisodeMinAggregateInputType
  _max?: AbhiCallCallerEpisodeMaxAggregateInputType
}

export type AbhiCallCallerEpisodeGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  userId: string
  callTitle: string
  callNotes: string | null
  isAnonymous: boolean
  transistorEpisodeId: string
  _count: AbhiCallCallerEpisodeCountAggregateOutputType | null
  _min: AbhiCallCallerEpisodeMinAggregateOutputType | null
  _max: AbhiCallCallerEpisodeMaxAggregateOutputType | null
}

export type GetAbhiCallCallerEpisodeGroupByPayload<T extends AbhiCallCallerEpisodeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AbhiCallCallerEpisodeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AbhiCallCallerEpisodeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AbhiCallCallerEpisodeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AbhiCallCallerEpisodeGroupByOutputType[P]>
      }
    >
  >



export type AbhiCallCallerEpisodeWhereInput = {
  AND?: Prisma.AbhiCallCallerEpisodeWhereInput | Prisma.AbhiCallCallerEpisodeWhereInput[]
  OR?: Prisma.AbhiCallCallerEpisodeWhereInput[]
  NOT?: Prisma.AbhiCallCallerEpisodeWhereInput | Prisma.AbhiCallCallerEpisodeWhereInput[]
  id?: Prisma.StringFilter<"AbhiCallCallerEpisode"> | string
  createdAt?: Prisma.DateTimeFilter<"AbhiCallCallerEpisode"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AbhiCallCallerEpisode"> | Date | string
  userId?: Prisma.StringFilter<"AbhiCallCallerEpisode"> | string
  callTitle?: Prisma.StringFilter<"AbhiCallCallerEpisode"> | string
  callNotes?: Prisma.StringNullableFilter<"AbhiCallCallerEpisode"> | string | null
  isAnonymous?: Prisma.BoolFilter<"AbhiCallCallerEpisode"> | boolean
  transistorEpisodeId?: Prisma.StringFilter<"AbhiCallCallerEpisode"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type AbhiCallCallerEpisodeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  callTitle?: Prisma.SortOrder
  callNotes?: Prisma.SortOrderInput | Prisma.SortOrder
  isAnonymous?: Prisma.SortOrder
  transistorEpisodeId?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type AbhiCallCallerEpisodeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  transistorEpisodeId?: string
  AND?: Prisma.AbhiCallCallerEpisodeWhereInput | Prisma.AbhiCallCallerEpisodeWhereInput[]
  OR?: Prisma.AbhiCallCallerEpisodeWhereInput[]
  NOT?: Prisma.AbhiCallCallerEpisodeWhereInput | Prisma.AbhiCallCallerEpisodeWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"AbhiCallCallerEpisode"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AbhiCallCallerEpisode"> | Date | string
  userId?: Prisma.StringFilter<"AbhiCallCallerEpisode"> | string
  callTitle?: Prisma.StringFilter<"AbhiCallCallerEpisode"> | string
  callNotes?: Prisma.StringNullableFilter<"AbhiCallCallerEpisode"> | string | null
  isAnonymous?: Prisma.BoolFilter<"AbhiCallCallerEpisode"> | boolean
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "transistorEpisodeId">

export type AbhiCallCallerEpisodeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  callTitle?: Prisma.SortOrder
  callNotes?: Prisma.SortOrderInput | Prisma.SortOrder
  isAnonymous?: Prisma.SortOrder
  transistorEpisodeId?: Prisma.SortOrder
  _count?: Prisma.AbhiCallCallerEpisodeCountOrderByAggregateInput
  _max?: Prisma.AbhiCallCallerEpisodeMaxOrderByAggregateInput
  _min?: Prisma.AbhiCallCallerEpisodeMinOrderByAggregateInput
}

export type AbhiCallCallerEpisodeScalarWhereWithAggregatesInput = {
  AND?: Prisma.AbhiCallCallerEpisodeScalarWhereWithAggregatesInput | Prisma.AbhiCallCallerEpisodeScalarWhereWithAggregatesInput[]
  OR?: Prisma.AbhiCallCallerEpisodeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AbhiCallCallerEpisodeScalarWhereWithAggregatesInput | Prisma.AbhiCallCallerEpisodeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AbhiCallCallerEpisode"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AbhiCallCallerEpisode"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AbhiCallCallerEpisode"> | Date | string
  userId?: Prisma.StringWithAggregatesFilter<"AbhiCallCallerEpisode"> | string
  callTitle?: Prisma.StringWithAggregatesFilter<"AbhiCallCallerEpisode"> | string
  callNotes?: Prisma.StringNullableWithAggregatesFilter<"AbhiCallCallerEpisode"> | string | null
  isAnonymous?: Prisma.BoolWithAggregatesFilter<"AbhiCallCallerEpisode"> | boolean
  transistorEpisodeId?: Prisma.StringWithAggregatesFilter<"AbhiCallCallerEpisode"> | string
}

export type AbhiCallCallerEpisodeCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  callTitle: string
  callNotes?: string | null
  isAnonymous?: boolean
  transistorEpisodeId: string
  user: Prisma.UserCreateNestedOneWithoutAbhiCallCallerEpisodesInput
}

export type AbhiCallCallerEpisodeUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  userId: string
  callTitle: string
  callNotes?: string | null
  isAnonymous?: boolean
  transistorEpisodeId: string
}

export type AbhiCallCallerEpisodeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  callTitle?: Prisma.StringFieldUpdateOperationsInput | string
  callNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  transistorEpisodeId?: Prisma.StringFieldUpdateOperationsInput | string
  user?: Prisma.UserUpdateOneRequiredWithoutAbhiCallCallerEpisodesNestedInput
}

export type AbhiCallCallerEpisodeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  callTitle?: Prisma.StringFieldUpdateOperationsInput | string
  callNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  transistorEpisodeId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AbhiCallCallerEpisodeCreateManyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  userId: string
  callTitle: string
  callNotes?: string | null
  isAnonymous?: boolean
  transistorEpisodeId: string
}

export type AbhiCallCallerEpisodeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  callTitle?: Prisma.StringFieldUpdateOperationsInput | string
  callNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  transistorEpisodeId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AbhiCallCallerEpisodeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  callTitle?: Prisma.StringFieldUpdateOperationsInput | string
  callNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  transistorEpisodeId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AbhiCallCallerEpisodeListRelationFilter = {
  every?: Prisma.AbhiCallCallerEpisodeWhereInput
  some?: Prisma.AbhiCallCallerEpisodeWhereInput
  none?: Prisma.AbhiCallCallerEpisodeWhereInput
}

export type AbhiCallCallerEpisodeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AbhiCallCallerEpisodeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  callTitle?: Prisma.SortOrder
  callNotes?: Prisma.SortOrder
  isAnonymous?: Prisma.SortOrder
  transistorEpisodeId?: Prisma.SortOrder
}

export type AbhiCallCallerEpisodeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  callTitle?: Prisma.SortOrder
  callNotes?: Prisma.SortOrder
  isAnonymous?: Prisma.SortOrder
  transistorEpisodeId?: Prisma.SortOrder
}

export type AbhiCallCallerEpisodeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  callTitle?: Prisma.SortOrder
  callNotes?: Prisma.SortOrder
  isAnonymous?: Prisma.SortOrder
  transistorEpisodeId?: Prisma.SortOrder
}

export type AbhiCallCallerEpisodeCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AbhiCallCallerEpisodeCreateWithoutUserInput, Prisma.AbhiCallCallerEpisodeUncheckedCreateWithoutUserInput> | Prisma.AbhiCallCallerEpisodeCreateWithoutUserInput[] | Prisma.AbhiCallCallerEpisodeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AbhiCallCallerEpisodeCreateOrConnectWithoutUserInput | Prisma.AbhiCallCallerEpisodeCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AbhiCallCallerEpisodeCreateManyUserInputEnvelope
  connect?: Prisma.AbhiCallCallerEpisodeWhereUniqueInput | Prisma.AbhiCallCallerEpisodeWhereUniqueInput[]
}

export type AbhiCallCallerEpisodeUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AbhiCallCallerEpisodeCreateWithoutUserInput, Prisma.AbhiCallCallerEpisodeUncheckedCreateWithoutUserInput> | Prisma.AbhiCallCallerEpisodeCreateWithoutUserInput[] | Prisma.AbhiCallCallerEpisodeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AbhiCallCallerEpisodeCreateOrConnectWithoutUserInput | Prisma.AbhiCallCallerEpisodeCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AbhiCallCallerEpisodeCreateManyUserInputEnvelope
  connect?: Prisma.AbhiCallCallerEpisodeWhereUniqueInput | Prisma.AbhiCallCallerEpisodeWhereUniqueInput[]
}

export type AbhiCallCallerEpisodeUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AbhiCallCallerEpisodeCreateWithoutUserInput, Prisma.AbhiCallCallerEpisodeUncheckedCreateWithoutUserInput> | Prisma.AbhiCallCallerEpisodeCreateWithoutUserInput[] | Prisma.AbhiCallCallerEpisodeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AbhiCallCallerEpisodeCreateOrConnectWithoutUserInput | Prisma.AbhiCallCallerEpisodeCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AbhiCallCallerEpisodeUpsertWithWhereUniqueWithoutUserInput | Prisma.AbhiCallCallerEpisodeUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AbhiCallCallerEpisodeCreateManyUserInputEnvelope
  set?: Prisma.AbhiCallCallerEpisodeWhereUniqueInput | Prisma.AbhiCallCallerEpisodeWhereUniqueInput[]
  disconnect?: Prisma.AbhiCallCallerEpisodeWhereUniqueInput | Prisma.AbhiCallCallerEpisodeWhereUniqueInput[]
  delete?: Prisma.AbhiCallCallerEpisodeWhereUniqueInput | Prisma.AbhiCallCallerEpisodeWhereUniqueInput[]
  connect?: Prisma.AbhiCallCallerEpisodeWhereUniqueInput | Prisma.AbhiCallCallerEpisodeWhereUniqueInput[]
  update?: Prisma.AbhiCallCallerEpisodeUpdateWithWhereUniqueWithoutUserInput | Prisma.AbhiCallCallerEpisodeUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AbhiCallCallerEpisodeUpdateManyWithWhereWithoutUserInput | Prisma.AbhiCallCallerEpisodeUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AbhiCallCallerEpisodeScalarWhereInput | Prisma.AbhiCallCallerEpisodeScalarWhereInput[]
}

export type AbhiCallCallerEpisodeUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AbhiCallCallerEpisodeCreateWithoutUserInput, Prisma.AbhiCallCallerEpisodeUncheckedCreateWithoutUserInput> | Prisma.AbhiCallCallerEpisodeCreateWithoutUserInput[] | Prisma.AbhiCallCallerEpisodeUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AbhiCallCallerEpisodeCreateOrConnectWithoutUserInput | Prisma.AbhiCallCallerEpisodeCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AbhiCallCallerEpisodeUpsertWithWhereUniqueWithoutUserInput | Prisma.AbhiCallCallerEpisodeUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AbhiCallCallerEpisodeCreateManyUserInputEnvelope
  set?: Prisma.AbhiCallCallerEpisodeWhereUniqueInput | Prisma.AbhiCallCallerEpisodeWhereUniqueInput[]
  disconnect?: Prisma.AbhiCallCallerEpisodeWhereUniqueInput | Prisma.AbhiCallCallerEpisodeWhereUniqueInput[]
  delete?: Prisma.AbhiCallCallerEpisodeWhereUniqueInput | Prisma.AbhiCallCallerEpisodeWhereUniqueInput[]
  connect?: Prisma.AbhiCallCallerEpisodeWhereUniqueInput | Prisma.AbhiCallCallerEpisodeWhereUniqueInput[]
  update?: Prisma.AbhiCallCallerEpisodeUpdateWithWhereUniqueWithoutUserInput | Prisma.AbhiCallCallerEpisodeUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AbhiCallCallerEpisodeUpdateManyWithWhereWithoutUserInput | Prisma.AbhiCallCallerEpisodeUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AbhiCallCallerEpisodeScalarWhereInput | Prisma.AbhiCallCallerEpisodeScalarWhereInput[]
}

export type AbhiCallCallerEpisodeCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  callTitle: string
  callNotes?: string | null
  isAnonymous?: boolean
  transistorEpisodeId: string
}

export type AbhiCallCallerEpisodeUncheckedCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  callTitle: string
  callNotes?: string | null
  isAnonymous?: boolean
  transistorEpisodeId: string
}

export type AbhiCallCallerEpisodeCreateOrConnectWithoutUserInput = {
  where: Prisma.AbhiCallCallerEpisodeWhereUniqueInput
  create: Prisma.XOR<Prisma.AbhiCallCallerEpisodeCreateWithoutUserInput, Prisma.AbhiCallCallerEpisodeUncheckedCreateWithoutUserInput>
}

export type AbhiCallCallerEpisodeCreateManyUserInputEnvelope = {
  data: Prisma.AbhiCallCallerEpisodeCreateManyUserInput | Prisma.AbhiCallCallerEpisodeCreateManyUserInput[]
}

export type AbhiCallCallerEpisodeUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.AbhiCallCallerEpisodeWhereUniqueInput
  update: Prisma.XOR<Prisma.AbhiCallCallerEpisodeUpdateWithoutUserInput, Prisma.AbhiCallCallerEpisodeUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.AbhiCallCallerEpisodeCreateWithoutUserInput, Prisma.AbhiCallCallerEpisodeUncheckedCreateWithoutUserInput>
}

export type AbhiCallCallerEpisodeUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.AbhiCallCallerEpisodeWhereUniqueInput
  data: Prisma.XOR<Prisma.AbhiCallCallerEpisodeUpdateWithoutUserInput, Prisma.AbhiCallCallerEpisodeUncheckedUpdateWithoutUserInput>
}

export type AbhiCallCallerEpisodeUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.AbhiCallCallerEpisodeScalarWhereInput
  data: Prisma.XOR<Prisma.AbhiCallCallerEpisodeUpdateManyMutationInput, Prisma.AbhiCallCallerEpisodeUncheckedUpdateManyWithoutUserInput>
}

export type AbhiCallCallerEpisodeScalarWhereInput = {
  AND?: Prisma.AbhiCallCallerEpisodeScalarWhereInput | Prisma.AbhiCallCallerEpisodeScalarWhereInput[]
  OR?: Prisma.AbhiCallCallerEpisodeScalarWhereInput[]
  NOT?: Prisma.AbhiCallCallerEpisodeScalarWhereInput | Prisma.AbhiCallCallerEpisodeScalarWhereInput[]
  id?: Prisma.StringFilter<"AbhiCallCallerEpisode"> | string
  createdAt?: Prisma.DateTimeFilter<"AbhiCallCallerEpisode"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AbhiCallCallerEpisode"> | Date | string
  userId?: Prisma.StringFilter<"AbhiCallCallerEpisode"> | string
  callTitle?: Prisma.StringFilter<"AbhiCallCallerEpisode"> | string
  callNotes?: Prisma.StringNullableFilter<"AbhiCallCallerEpisode"> | string | null
  isAnonymous?: Prisma.BoolFilter<"AbhiCallCallerEpisode"> | boolean
  transistorEpisodeId?: Prisma.StringFilter<"AbhiCallCallerEpisode"> | string
}

export type AbhiCallCallerEpisodeCreateManyUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  callTitle: string
  callNotes?: string | null
  isAnonymous?: boolean
  transistorEpisodeId: string
}

export type AbhiCallCallerEpisodeUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  callTitle?: Prisma.StringFieldUpdateOperationsInput | string
  callNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  transistorEpisodeId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AbhiCallCallerEpisodeUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  callTitle?: Prisma.StringFieldUpdateOperationsInput | string
  callNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  transistorEpisodeId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AbhiCallCallerEpisodeUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  callTitle?: Prisma.StringFieldUpdateOperationsInput | string
  callNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isAnonymous?: Prisma.BoolFieldUpdateOperationsInput | boolean
  transistorEpisodeId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type AbhiCallCallerEpisodeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  callTitle?: boolean
  callNotes?: boolean
  isAnonymous?: boolean
  transistorEpisodeId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["abhiCallCallerEpisode"]>

export type AbhiCallCallerEpisodeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  callTitle?: boolean
  callNotes?: boolean
  isAnonymous?: boolean
  transistorEpisodeId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["abhiCallCallerEpisode"]>

export type AbhiCallCallerEpisodeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  callTitle?: boolean
  callNotes?: boolean
  isAnonymous?: boolean
  transistorEpisodeId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["abhiCallCallerEpisode"]>

export type AbhiCallCallerEpisodeSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  callTitle?: boolean
  callNotes?: boolean
  isAnonymous?: boolean
  transistorEpisodeId?: boolean
}

export type AbhiCallCallerEpisodeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "userId" | "callTitle" | "callNotes" | "isAnonymous" | "transistorEpisodeId", ExtArgs["result"]["abhiCallCallerEpisode"]>
export type AbhiCallCallerEpisodeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type AbhiCallCallerEpisodeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type AbhiCallCallerEpisodeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $AbhiCallCallerEpisodePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AbhiCallCallerEpisode"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    userId: string
    callTitle: string
    callNotes: string | null
    isAnonymous: boolean
    transistorEpisodeId: string
  }, ExtArgs["result"]["abhiCallCallerEpisode"]>
  composites: {}
}

export type AbhiCallCallerEpisodeGetPayload<S extends boolean | null | undefined | AbhiCallCallerEpisodeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AbhiCallCallerEpisodePayload, S>

export type AbhiCallCallerEpisodeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AbhiCallCallerEpisodeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AbhiCallCallerEpisodeCountAggregateInputType | true
  }

export interface AbhiCallCallerEpisodeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AbhiCallCallerEpisode'], meta: { name: 'AbhiCallCallerEpisode' } }
  /**
   * Find zero or one AbhiCallCallerEpisode that matches the filter.
   * @param {AbhiCallCallerEpisodeFindUniqueArgs} args - Arguments to find a AbhiCallCallerEpisode
   * @example
   * // Get one AbhiCallCallerEpisode
   * const abhiCallCallerEpisode = await prisma.abhiCallCallerEpisode.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AbhiCallCallerEpisodeFindUniqueArgs>(args: Prisma.SelectSubset<T, AbhiCallCallerEpisodeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AbhiCallCallerEpisodeClient<runtime.Types.Result.GetResult<Prisma.$AbhiCallCallerEpisodePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AbhiCallCallerEpisode that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AbhiCallCallerEpisodeFindUniqueOrThrowArgs} args - Arguments to find a AbhiCallCallerEpisode
   * @example
   * // Get one AbhiCallCallerEpisode
   * const abhiCallCallerEpisode = await prisma.abhiCallCallerEpisode.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AbhiCallCallerEpisodeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AbhiCallCallerEpisodeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AbhiCallCallerEpisodeClient<runtime.Types.Result.GetResult<Prisma.$AbhiCallCallerEpisodePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AbhiCallCallerEpisode that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbhiCallCallerEpisodeFindFirstArgs} args - Arguments to find a AbhiCallCallerEpisode
   * @example
   * // Get one AbhiCallCallerEpisode
   * const abhiCallCallerEpisode = await prisma.abhiCallCallerEpisode.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AbhiCallCallerEpisodeFindFirstArgs>(args?: Prisma.SelectSubset<T, AbhiCallCallerEpisodeFindFirstArgs<ExtArgs>>): Prisma.Prisma__AbhiCallCallerEpisodeClient<runtime.Types.Result.GetResult<Prisma.$AbhiCallCallerEpisodePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AbhiCallCallerEpisode that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbhiCallCallerEpisodeFindFirstOrThrowArgs} args - Arguments to find a AbhiCallCallerEpisode
   * @example
   * // Get one AbhiCallCallerEpisode
   * const abhiCallCallerEpisode = await prisma.abhiCallCallerEpisode.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AbhiCallCallerEpisodeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AbhiCallCallerEpisodeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AbhiCallCallerEpisodeClient<runtime.Types.Result.GetResult<Prisma.$AbhiCallCallerEpisodePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AbhiCallCallerEpisodes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbhiCallCallerEpisodeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AbhiCallCallerEpisodes
   * const abhiCallCallerEpisodes = await prisma.abhiCallCallerEpisode.findMany()
   * 
   * // Get first 10 AbhiCallCallerEpisodes
   * const abhiCallCallerEpisodes = await prisma.abhiCallCallerEpisode.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const abhiCallCallerEpisodeWithIdOnly = await prisma.abhiCallCallerEpisode.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AbhiCallCallerEpisodeFindManyArgs>(args?: Prisma.SelectSubset<T, AbhiCallCallerEpisodeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AbhiCallCallerEpisodePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AbhiCallCallerEpisode.
   * @param {AbhiCallCallerEpisodeCreateArgs} args - Arguments to create a AbhiCallCallerEpisode.
   * @example
   * // Create one AbhiCallCallerEpisode
   * const AbhiCallCallerEpisode = await prisma.abhiCallCallerEpisode.create({
   *   data: {
   *     // ... data to create a AbhiCallCallerEpisode
   *   }
   * })
   * 
   */
  create<T extends AbhiCallCallerEpisodeCreateArgs>(args: Prisma.SelectSubset<T, AbhiCallCallerEpisodeCreateArgs<ExtArgs>>): Prisma.Prisma__AbhiCallCallerEpisodeClient<runtime.Types.Result.GetResult<Prisma.$AbhiCallCallerEpisodePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AbhiCallCallerEpisodes.
   * @param {AbhiCallCallerEpisodeCreateManyArgs} args - Arguments to create many AbhiCallCallerEpisodes.
   * @example
   * // Create many AbhiCallCallerEpisodes
   * const abhiCallCallerEpisode = await prisma.abhiCallCallerEpisode.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AbhiCallCallerEpisodeCreateManyArgs>(args?: Prisma.SelectSubset<T, AbhiCallCallerEpisodeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AbhiCallCallerEpisodes and returns the data saved in the database.
   * @param {AbhiCallCallerEpisodeCreateManyAndReturnArgs} args - Arguments to create many AbhiCallCallerEpisodes.
   * @example
   * // Create many AbhiCallCallerEpisodes
   * const abhiCallCallerEpisode = await prisma.abhiCallCallerEpisode.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AbhiCallCallerEpisodes and only return the `id`
   * const abhiCallCallerEpisodeWithIdOnly = await prisma.abhiCallCallerEpisode.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AbhiCallCallerEpisodeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AbhiCallCallerEpisodeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AbhiCallCallerEpisodePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AbhiCallCallerEpisode.
   * @param {AbhiCallCallerEpisodeDeleteArgs} args - Arguments to delete one AbhiCallCallerEpisode.
   * @example
   * // Delete one AbhiCallCallerEpisode
   * const AbhiCallCallerEpisode = await prisma.abhiCallCallerEpisode.delete({
   *   where: {
   *     // ... filter to delete one AbhiCallCallerEpisode
   *   }
   * })
   * 
   */
  delete<T extends AbhiCallCallerEpisodeDeleteArgs>(args: Prisma.SelectSubset<T, AbhiCallCallerEpisodeDeleteArgs<ExtArgs>>): Prisma.Prisma__AbhiCallCallerEpisodeClient<runtime.Types.Result.GetResult<Prisma.$AbhiCallCallerEpisodePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AbhiCallCallerEpisode.
   * @param {AbhiCallCallerEpisodeUpdateArgs} args - Arguments to update one AbhiCallCallerEpisode.
   * @example
   * // Update one AbhiCallCallerEpisode
   * const abhiCallCallerEpisode = await prisma.abhiCallCallerEpisode.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AbhiCallCallerEpisodeUpdateArgs>(args: Prisma.SelectSubset<T, AbhiCallCallerEpisodeUpdateArgs<ExtArgs>>): Prisma.Prisma__AbhiCallCallerEpisodeClient<runtime.Types.Result.GetResult<Prisma.$AbhiCallCallerEpisodePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AbhiCallCallerEpisodes.
   * @param {AbhiCallCallerEpisodeDeleteManyArgs} args - Arguments to filter AbhiCallCallerEpisodes to delete.
   * @example
   * // Delete a few AbhiCallCallerEpisodes
   * const { count } = await prisma.abhiCallCallerEpisode.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AbhiCallCallerEpisodeDeleteManyArgs>(args?: Prisma.SelectSubset<T, AbhiCallCallerEpisodeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AbhiCallCallerEpisodes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbhiCallCallerEpisodeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AbhiCallCallerEpisodes
   * const abhiCallCallerEpisode = await prisma.abhiCallCallerEpisode.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AbhiCallCallerEpisodeUpdateManyArgs>(args: Prisma.SelectSubset<T, AbhiCallCallerEpisodeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AbhiCallCallerEpisodes and returns the data updated in the database.
   * @param {AbhiCallCallerEpisodeUpdateManyAndReturnArgs} args - Arguments to update many AbhiCallCallerEpisodes.
   * @example
   * // Update many AbhiCallCallerEpisodes
   * const abhiCallCallerEpisode = await prisma.abhiCallCallerEpisode.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AbhiCallCallerEpisodes and only return the `id`
   * const abhiCallCallerEpisodeWithIdOnly = await prisma.abhiCallCallerEpisode.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AbhiCallCallerEpisodeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AbhiCallCallerEpisodeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AbhiCallCallerEpisodePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AbhiCallCallerEpisode.
   * @param {AbhiCallCallerEpisodeUpsertArgs} args - Arguments to update or create a AbhiCallCallerEpisode.
   * @example
   * // Update or create a AbhiCallCallerEpisode
   * const abhiCallCallerEpisode = await prisma.abhiCallCallerEpisode.upsert({
   *   create: {
   *     // ... data to create a AbhiCallCallerEpisode
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AbhiCallCallerEpisode we want to update
   *   }
   * })
   */
  upsert<T extends AbhiCallCallerEpisodeUpsertArgs>(args: Prisma.SelectSubset<T, AbhiCallCallerEpisodeUpsertArgs<ExtArgs>>): Prisma.Prisma__AbhiCallCallerEpisodeClient<runtime.Types.Result.GetResult<Prisma.$AbhiCallCallerEpisodePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AbhiCallCallerEpisodes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbhiCallCallerEpisodeCountArgs} args - Arguments to filter AbhiCallCallerEpisodes to count.
   * @example
   * // Count the number of AbhiCallCallerEpisodes
   * const count = await prisma.abhiCallCallerEpisode.count({
   *   where: {
   *     // ... the filter for the AbhiCallCallerEpisodes we want to count
   *   }
   * })
  **/
  count<T extends AbhiCallCallerEpisodeCountArgs>(
    args?: Prisma.Subset<T, AbhiCallCallerEpisodeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AbhiCallCallerEpisodeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AbhiCallCallerEpisode.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbhiCallCallerEpisodeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AbhiCallCallerEpisodeAggregateArgs>(args: Prisma.Subset<T, AbhiCallCallerEpisodeAggregateArgs>): Prisma.PrismaPromise<GetAbhiCallCallerEpisodeAggregateType<T>>

  /**
   * Group by AbhiCallCallerEpisode.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AbhiCallCallerEpisodeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AbhiCallCallerEpisodeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AbhiCallCallerEpisodeGroupByArgs['orderBy'] }
      : { orderBy?: AbhiCallCallerEpisodeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AbhiCallCallerEpisodeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAbhiCallCallerEpisodeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AbhiCallCallerEpisode model
 */
readonly fields: AbhiCallCallerEpisodeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AbhiCallCallerEpisode.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AbhiCallCallerEpisodeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AbhiCallCallerEpisode model
 */
export interface AbhiCallCallerEpisodeFieldRefs {
  readonly id: Prisma.FieldRef<"AbhiCallCallerEpisode", 'String'>
  readonly createdAt: Prisma.FieldRef<"AbhiCallCallerEpisode", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AbhiCallCallerEpisode", 'DateTime'>
  readonly userId: Prisma.FieldRef<"AbhiCallCallerEpisode", 'String'>
  readonly callTitle: Prisma.FieldRef<"AbhiCallCallerEpisode", 'String'>
  readonly callNotes: Prisma.FieldRef<"AbhiCallCallerEpisode", 'String'>
  readonly isAnonymous: Prisma.FieldRef<"AbhiCallCallerEpisode", 'Boolean'>
  readonly transistorEpisodeId: Prisma.FieldRef<"AbhiCallCallerEpisode", 'String'>
}
    

// Custom InputTypes
/**
 * AbhiCallCallerEpisode findUnique
 */
export type AbhiCallCallerEpisodeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AbhiCallCallerEpisode
   */
  select?: Prisma.AbhiCallCallerEpisodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AbhiCallCallerEpisode
   */
  omit?: Prisma.AbhiCallCallerEpisodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbhiCallCallerEpisodeInclude<ExtArgs> | null
  /**
   * Filter, which AbhiCallCallerEpisode to fetch.
   */
  where: Prisma.AbhiCallCallerEpisodeWhereUniqueInput
}

/**
 * AbhiCallCallerEpisode findUniqueOrThrow
 */
export type AbhiCallCallerEpisodeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AbhiCallCallerEpisode
   */
  select?: Prisma.AbhiCallCallerEpisodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AbhiCallCallerEpisode
   */
  omit?: Prisma.AbhiCallCallerEpisodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbhiCallCallerEpisodeInclude<ExtArgs> | null
  /**
   * Filter, which AbhiCallCallerEpisode to fetch.
   */
  where: Prisma.AbhiCallCallerEpisodeWhereUniqueInput
}

/**
 * AbhiCallCallerEpisode findFirst
 */
export type AbhiCallCallerEpisodeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AbhiCallCallerEpisode
   */
  select?: Prisma.AbhiCallCallerEpisodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AbhiCallCallerEpisode
   */
  omit?: Prisma.AbhiCallCallerEpisodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbhiCallCallerEpisodeInclude<ExtArgs> | null
  /**
   * Filter, which AbhiCallCallerEpisode to fetch.
   */
  where?: Prisma.AbhiCallCallerEpisodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AbhiCallCallerEpisodes to fetch.
   */
  orderBy?: Prisma.AbhiCallCallerEpisodeOrderByWithRelationInput | Prisma.AbhiCallCallerEpisodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AbhiCallCallerEpisodes.
   */
  cursor?: Prisma.AbhiCallCallerEpisodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AbhiCallCallerEpisodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AbhiCallCallerEpisodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AbhiCallCallerEpisodes.
   */
  distinct?: Prisma.AbhiCallCallerEpisodeScalarFieldEnum | Prisma.AbhiCallCallerEpisodeScalarFieldEnum[]
}

/**
 * AbhiCallCallerEpisode findFirstOrThrow
 */
export type AbhiCallCallerEpisodeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AbhiCallCallerEpisode
   */
  select?: Prisma.AbhiCallCallerEpisodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AbhiCallCallerEpisode
   */
  omit?: Prisma.AbhiCallCallerEpisodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbhiCallCallerEpisodeInclude<ExtArgs> | null
  /**
   * Filter, which AbhiCallCallerEpisode to fetch.
   */
  where?: Prisma.AbhiCallCallerEpisodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AbhiCallCallerEpisodes to fetch.
   */
  orderBy?: Prisma.AbhiCallCallerEpisodeOrderByWithRelationInput | Prisma.AbhiCallCallerEpisodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AbhiCallCallerEpisodes.
   */
  cursor?: Prisma.AbhiCallCallerEpisodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AbhiCallCallerEpisodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AbhiCallCallerEpisodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AbhiCallCallerEpisodes.
   */
  distinct?: Prisma.AbhiCallCallerEpisodeScalarFieldEnum | Prisma.AbhiCallCallerEpisodeScalarFieldEnum[]
}

/**
 * AbhiCallCallerEpisode findMany
 */
export type AbhiCallCallerEpisodeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AbhiCallCallerEpisode
   */
  select?: Prisma.AbhiCallCallerEpisodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AbhiCallCallerEpisode
   */
  omit?: Prisma.AbhiCallCallerEpisodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbhiCallCallerEpisodeInclude<ExtArgs> | null
  /**
   * Filter, which AbhiCallCallerEpisodes to fetch.
   */
  where?: Prisma.AbhiCallCallerEpisodeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AbhiCallCallerEpisodes to fetch.
   */
  orderBy?: Prisma.AbhiCallCallerEpisodeOrderByWithRelationInput | Prisma.AbhiCallCallerEpisodeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AbhiCallCallerEpisodes.
   */
  cursor?: Prisma.AbhiCallCallerEpisodeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AbhiCallCallerEpisodes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AbhiCallCallerEpisodes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AbhiCallCallerEpisodes.
   */
  distinct?: Prisma.AbhiCallCallerEpisodeScalarFieldEnum | Prisma.AbhiCallCallerEpisodeScalarFieldEnum[]
}

/**
 * AbhiCallCallerEpisode create
 */
export type AbhiCallCallerEpisodeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AbhiCallCallerEpisode
   */
  select?: Prisma.AbhiCallCallerEpisodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AbhiCallCallerEpisode
   */
  omit?: Prisma.AbhiCallCallerEpisodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbhiCallCallerEpisodeInclude<ExtArgs> | null
  /**
   * The data needed to create a AbhiCallCallerEpisode.
   */
  data: Prisma.XOR<Prisma.AbhiCallCallerEpisodeCreateInput, Prisma.AbhiCallCallerEpisodeUncheckedCreateInput>
}

/**
 * AbhiCallCallerEpisode createMany
 */
export type AbhiCallCallerEpisodeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AbhiCallCallerEpisodes.
   */
  data: Prisma.AbhiCallCallerEpisodeCreateManyInput | Prisma.AbhiCallCallerEpisodeCreateManyInput[]
}

/**
 * AbhiCallCallerEpisode createManyAndReturn
 */
export type AbhiCallCallerEpisodeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AbhiCallCallerEpisode
   */
  select?: Prisma.AbhiCallCallerEpisodeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AbhiCallCallerEpisode
   */
  omit?: Prisma.AbhiCallCallerEpisodeOmit<ExtArgs> | null
  /**
   * The data used to create many AbhiCallCallerEpisodes.
   */
  data: Prisma.AbhiCallCallerEpisodeCreateManyInput | Prisma.AbhiCallCallerEpisodeCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbhiCallCallerEpisodeIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AbhiCallCallerEpisode update
 */
export type AbhiCallCallerEpisodeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AbhiCallCallerEpisode
   */
  select?: Prisma.AbhiCallCallerEpisodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AbhiCallCallerEpisode
   */
  omit?: Prisma.AbhiCallCallerEpisodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbhiCallCallerEpisodeInclude<ExtArgs> | null
  /**
   * The data needed to update a AbhiCallCallerEpisode.
   */
  data: Prisma.XOR<Prisma.AbhiCallCallerEpisodeUpdateInput, Prisma.AbhiCallCallerEpisodeUncheckedUpdateInput>
  /**
   * Choose, which AbhiCallCallerEpisode to update.
   */
  where: Prisma.AbhiCallCallerEpisodeWhereUniqueInput
}

/**
 * AbhiCallCallerEpisode updateMany
 */
export type AbhiCallCallerEpisodeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AbhiCallCallerEpisodes.
   */
  data: Prisma.XOR<Prisma.AbhiCallCallerEpisodeUpdateManyMutationInput, Prisma.AbhiCallCallerEpisodeUncheckedUpdateManyInput>
  /**
   * Filter which AbhiCallCallerEpisodes to update
   */
  where?: Prisma.AbhiCallCallerEpisodeWhereInput
  /**
   * Limit how many AbhiCallCallerEpisodes to update.
   */
  limit?: number
}

/**
 * AbhiCallCallerEpisode updateManyAndReturn
 */
export type AbhiCallCallerEpisodeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AbhiCallCallerEpisode
   */
  select?: Prisma.AbhiCallCallerEpisodeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AbhiCallCallerEpisode
   */
  omit?: Prisma.AbhiCallCallerEpisodeOmit<ExtArgs> | null
  /**
   * The data used to update AbhiCallCallerEpisodes.
   */
  data: Prisma.XOR<Prisma.AbhiCallCallerEpisodeUpdateManyMutationInput, Prisma.AbhiCallCallerEpisodeUncheckedUpdateManyInput>
  /**
   * Filter which AbhiCallCallerEpisodes to update
   */
  where?: Prisma.AbhiCallCallerEpisodeWhereInput
  /**
   * Limit how many AbhiCallCallerEpisodes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbhiCallCallerEpisodeIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AbhiCallCallerEpisode upsert
 */
export type AbhiCallCallerEpisodeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AbhiCallCallerEpisode
   */
  select?: Prisma.AbhiCallCallerEpisodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AbhiCallCallerEpisode
   */
  omit?: Prisma.AbhiCallCallerEpisodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbhiCallCallerEpisodeInclude<ExtArgs> | null
  /**
   * The filter to search for the AbhiCallCallerEpisode to update in case it exists.
   */
  where: Prisma.AbhiCallCallerEpisodeWhereUniqueInput
  /**
   * In case the AbhiCallCallerEpisode found by the `where` argument doesn't exist, create a new AbhiCallCallerEpisode with this data.
   */
  create: Prisma.XOR<Prisma.AbhiCallCallerEpisodeCreateInput, Prisma.AbhiCallCallerEpisodeUncheckedCreateInput>
  /**
   * In case the AbhiCallCallerEpisode was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AbhiCallCallerEpisodeUpdateInput, Prisma.AbhiCallCallerEpisodeUncheckedUpdateInput>
}

/**
 * AbhiCallCallerEpisode delete
 */
export type AbhiCallCallerEpisodeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AbhiCallCallerEpisode
   */
  select?: Prisma.AbhiCallCallerEpisodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AbhiCallCallerEpisode
   */
  omit?: Prisma.AbhiCallCallerEpisodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbhiCallCallerEpisodeInclude<ExtArgs> | null
  /**
   * Filter which AbhiCallCallerEpisode to delete.
   */
  where: Prisma.AbhiCallCallerEpisodeWhereUniqueInput
}

/**
 * AbhiCallCallerEpisode deleteMany
 */
export type AbhiCallCallerEpisodeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AbhiCallCallerEpisodes to delete
   */
  where?: Prisma.AbhiCallCallerEpisodeWhereInput
  /**
   * Limit how many AbhiCallCallerEpisodes to delete.
   */
  limit?: number
}

/**
 * AbhiCallCallerEpisode without action
 */
export type AbhiCallCallerEpisodeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AbhiCallCallerEpisode
   */
  select?: Prisma.AbhiCallCallerEpisodeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AbhiCallCallerEpisode
   */
  omit?: Prisma.AbhiCallCallerEpisodeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbhiCallCallerEpisodeInclude<ExtArgs> | null
}
