
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `HomeworkCompletion` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model HomeworkCompletion
 * 
 */
export type HomeworkCompletionModel = runtime.Types.Result.DefaultSelection<Prisma.$HomeworkCompletionPayload>

export type AggregateHomeworkCompletion = {
  _count: HomeworkCompletionCountAggregateOutputType | null
  _avg: HomeworkCompletionAvgAggregateOutputType | null
  _sum: HomeworkCompletionSumAggregateOutputType | null
  _min: HomeworkCompletionMinAggregateOutputType | null
  _max: HomeworkCompletionMaxAggregateOutputType | null
}

export type HomeworkCompletionAvgAggregateOutputType = {
  seasonNumber: number | null
  episodeNumber: number | null
  itemIndex: number | null
}

export type HomeworkCompletionSumAggregateOutputType = {
  seasonNumber: number | null
  episodeNumber: number | null
  itemIndex: number | null
}

export type HomeworkCompletionMinAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  userId: string | null
  clientId: string | null
  seasonNumber: number | null
  episodeNumber: number | null
  itemIndex: number | null
}

export type HomeworkCompletionMaxAggregateOutputType = {
  id: string | null
  createdAt: Date | null
  updatedAt: Date | null
  userId: string | null
  clientId: string | null
  seasonNumber: number | null
  episodeNumber: number | null
  itemIndex: number | null
}

export type HomeworkCompletionCountAggregateOutputType = {
  id: number
  createdAt: number
  updatedAt: number
  userId: number
  clientId: number
  seasonNumber: number
  episodeNumber: number
  itemIndex: number
  _all: number
}


export type HomeworkCompletionAvgAggregateInputType = {
  seasonNumber?: true
  episodeNumber?: true
  itemIndex?: true
}

export type HomeworkCompletionSumAggregateInputType = {
  seasonNumber?: true
  episodeNumber?: true
  itemIndex?: true
}

export type HomeworkCompletionMinAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
  clientId?: true
  seasonNumber?: true
  episodeNumber?: true
  itemIndex?: true
}

export type HomeworkCompletionMaxAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
  clientId?: true
  seasonNumber?: true
  episodeNumber?: true
  itemIndex?: true
}

export type HomeworkCompletionCountAggregateInputType = {
  id?: true
  createdAt?: true
  updatedAt?: true
  userId?: true
  clientId?: true
  seasonNumber?: true
  episodeNumber?: true
  itemIndex?: true
  _all?: true
}

export type HomeworkCompletionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which HomeworkCompletion to aggregate.
   */
  where?: Prisma.HomeworkCompletionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HomeworkCompletions to fetch.
   */
  orderBy?: Prisma.HomeworkCompletionOrderByWithRelationInput | Prisma.HomeworkCompletionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.HomeworkCompletionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HomeworkCompletions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HomeworkCompletions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned HomeworkCompletions
  **/
  _count?: true | HomeworkCompletionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: HomeworkCompletionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: HomeworkCompletionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: HomeworkCompletionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: HomeworkCompletionMaxAggregateInputType
}

export type GetHomeworkCompletionAggregateType<T extends HomeworkCompletionAggregateArgs> = {
      [P in keyof T & keyof AggregateHomeworkCompletion]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateHomeworkCompletion[P]>
    : Prisma.GetScalarType<T[P], AggregateHomeworkCompletion[P]>
}




export type HomeworkCompletionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HomeworkCompletionWhereInput
  orderBy?: Prisma.HomeworkCompletionOrderByWithAggregationInput | Prisma.HomeworkCompletionOrderByWithAggregationInput[]
  by: Prisma.HomeworkCompletionScalarFieldEnum[] | Prisma.HomeworkCompletionScalarFieldEnum
  having?: Prisma.HomeworkCompletionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: HomeworkCompletionCountAggregateInputType | true
  _avg?: HomeworkCompletionAvgAggregateInputType
  _sum?: HomeworkCompletionSumAggregateInputType
  _min?: HomeworkCompletionMinAggregateInputType
  _max?: HomeworkCompletionMaxAggregateInputType
}

export type HomeworkCompletionGroupByOutputType = {
  id: string
  createdAt: Date
  updatedAt: Date
  userId: string | null
  clientId: string | null
  seasonNumber: number
  episodeNumber: number
  itemIndex: number
  _count: HomeworkCompletionCountAggregateOutputType | null
  _avg: HomeworkCompletionAvgAggregateOutputType | null
  _sum: HomeworkCompletionSumAggregateOutputType | null
  _min: HomeworkCompletionMinAggregateOutputType | null
  _max: HomeworkCompletionMaxAggregateOutputType | null
}

export type GetHomeworkCompletionGroupByPayload<T extends HomeworkCompletionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<HomeworkCompletionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof HomeworkCompletionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], HomeworkCompletionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], HomeworkCompletionGroupByOutputType[P]>
      }
    >
  >



export type HomeworkCompletionWhereInput = {
  AND?: Prisma.HomeworkCompletionWhereInput | Prisma.HomeworkCompletionWhereInput[]
  OR?: Prisma.HomeworkCompletionWhereInput[]
  NOT?: Prisma.HomeworkCompletionWhereInput | Prisma.HomeworkCompletionWhereInput[]
  id?: Prisma.StringFilter<"HomeworkCompletion"> | string
  createdAt?: Prisma.DateTimeFilter<"HomeworkCompletion"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"HomeworkCompletion"> | Date | string
  userId?: Prisma.StringNullableFilter<"HomeworkCompletion"> | string | null
  clientId?: Prisma.StringNullableFilter<"HomeworkCompletion"> | string | null
  seasonNumber?: Prisma.IntFilter<"HomeworkCompletion"> | number
  episodeNumber?: Prisma.IntFilter<"HomeworkCompletion"> | number
  itemIndex?: Prisma.IntFilter<"HomeworkCompletion"> | number
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type HomeworkCompletionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  clientId?: Prisma.SortOrderInput | Prisma.SortOrder
  seasonNumber?: Prisma.SortOrder
  episodeNumber?: Prisma.SortOrder
  itemIndex?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type HomeworkCompletionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_seasonNumber_episodeNumber_itemIndex?: Prisma.HomeworkCompletionUserIdSeasonNumberEpisodeNumberItemIndexCompoundUniqueInput
  clientId_seasonNumber_episodeNumber_itemIndex?: Prisma.HomeworkCompletionClientIdSeasonNumberEpisodeNumberItemIndexCompoundUniqueInput
  AND?: Prisma.HomeworkCompletionWhereInput | Prisma.HomeworkCompletionWhereInput[]
  OR?: Prisma.HomeworkCompletionWhereInput[]
  NOT?: Prisma.HomeworkCompletionWhereInput | Prisma.HomeworkCompletionWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"HomeworkCompletion"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"HomeworkCompletion"> | Date | string
  userId?: Prisma.StringNullableFilter<"HomeworkCompletion"> | string | null
  clientId?: Prisma.StringNullableFilter<"HomeworkCompletion"> | string | null
  seasonNumber?: Prisma.IntFilter<"HomeworkCompletion"> | number
  episodeNumber?: Prisma.IntFilter<"HomeworkCompletion"> | number
  itemIndex?: Prisma.IntFilter<"HomeworkCompletion"> | number
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id" | "userId_seasonNumber_episodeNumber_itemIndex" | "clientId_seasonNumber_episodeNumber_itemIndex">

export type HomeworkCompletionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  clientId?: Prisma.SortOrderInput | Prisma.SortOrder
  seasonNumber?: Prisma.SortOrder
  episodeNumber?: Prisma.SortOrder
  itemIndex?: Prisma.SortOrder
  _count?: Prisma.HomeworkCompletionCountOrderByAggregateInput
  _avg?: Prisma.HomeworkCompletionAvgOrderByAggregateInput
  _max?: Prisma.HomeworkCompletionMaxOrderByAggregateInput
  _min?: Prisma.HomeworkCompletionMinOrderByAggregateInput
  _sum?: Prisma.HomeworkCompletionSumOrderByAggregateInput
}

export type HomeworkCompletionScalarWhereWithAggregatesInput = {
  AND?: Prisma.HomeworkCompletionScalarWhereWithAggregatesInput | Prisma.HomeworkCompletionScalarWhereWithAggregatesInput[]
  OR?: Prisma.HomeworkCompletionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.HomeworkCompletionScalarWhereWithAggregatesInput | Prisma.HomeworkCompletionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"HomeworkCompletion"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"HomeworkCompletion"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"HomeworkCompletion"> | Date | string
  userId?: Prisma.StringNullableWithAggregatesFilter<"HomeworkCompletion"> | string | null
  clientId?: Prisma.StringNullableWithAggregatesFilter<"HomeworkCompletion"> | string | null
  seasonNumber?: Prisma.IntWithAggregatesFilter<"HomeworkCompletion"> | number
  episodeNumber?: Prisma.IntWithAggregatesFilter<"HomeworkCompletion"> | number
  itemIndex?: Prisma.IntWithAggregatesFilter<"HomeworkCompletion"> | number
}

export type HomeworkCompletionCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  clientId?: string | null
  seasonNumber: number
  episodeNumber: number
  itemIndex: number
  user?: Prisma.UserCreateNestedOneWithoutHomeworkCompletionsInput
}

export type HomeworkCompletionUncheckedCreateInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  userId?: string | null
  clientId?: string | null
  seasonNumber: number
  episodeNumber: number
  itemIndex: number
}

export type HomeworkCompletionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  clientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seasonNumber?: Prisma.IntFieldUpdateOperationsInput | number
  episodeNumber?: Prisma.IntFieldUpdateOperationsInput | number
  itemIndex?: Prisma.IntFieldUpdateOperationsInput | number
  user?: Prisma.UserUpdateOneWithoutHomeworkCompletionsNestedInput
}

export type HomeworkCompletionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seasonNumber?: Prisma.IntFieldUpdateOperationsInput | number
  episodeNumber?: Prisma.IntFieldUpdateOperationsInput | number
  itemIndex?: Prisma.IntFieldUpdateOperationsInput | number
}

export type HomeworkCompletionCreateManyInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  userId?: string | null
  clientId?: string | null
  seasonNumber: number
  episodeNumber: number
  itemIndex: number
}

export type HomeworkCompletionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  clientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seasonNumber?: Prisma.IntFieldUpdateOperationsInput | number
  episodeNumber?: Prisma.IntFieldUpdateOperationsInput | number
  itemIndex?: Prisma.IntFieldUpdateOperationsInput | number
}

export type HomeworkCompletionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  clientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seasonNumber?: Prisma.IntFieldUpdateOperationsInput | number
  episodeNumber?: Prisma.IntFieldUpdateOperationsInput | number
  itemIndex?: Prisma.IntFieldUpdateOperationsInput | number
}

export type HomeworkCompletionListRelationFilter = {
  every?: Prisma.HomeworkCompletionWhereInput
  some?: Prisma.HomeworkCompletionWhereInput
  none?: Prisma.HomeworkCompletionWhereInput
}

export type HomeworkCompletionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type HomeworkCompletionUserIdSeasonNumberEpisodeNumberItemIndexCompoundUniqueInput = {
  userId: string
  seasonNumber: number
  episodeNumber: number
  itemIndex: number
}

export type HomeworkCompletionClientIdSeasonNumberEpisodeNumberItemIndexCompoundUniqueInput = {
  clientId: string
  seasonNumber: number
  episodeNumber: number
  itemIndex: number
}

export type HomeworkCompletionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  seasonNumber?: Prisma.SortOrder
  episodeNumber?: Prisma.SortOrder
  itemIndex?: Prisma.SortOrder
}

export type HomeworkCompletionAvgOrderByAggregateInput = {
  seasonNumber?: Prisma.SortOrder
  episodeNumber?: Prisma.SortOrder
  itemIndex?: Prisma.SortOrder
}

export type HomeworkCompletionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  seasonNumber?: Prisma.SortOrder
  episodeNumber?: Prisma.SortOrder
  itemIndex?: Prisma.SortOrder
}

export type HomeworkCompletionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  clientId?: Prisma.SortOrder
  seasonNumber?: Prisma.SortOrder
  episodeNumber?: Prisma.SortOrder
  itemIndex?: Prisma.SortOrder
}

export type HomeworkCompletionSumOrderByAggregateInput = {
  seasonNumber?: Prisma.SortOrder
  episodeNumber?: Prisma.SortOrder
  itemIndex?: Prisma.SortOrder
}

export type HomeworkCompletionCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.HomeworkCompletionCreateWithoutUserInput, Prisma.HomeworkCompletionUncheckedCreateWithoutUserInput> | Prisma.HomeworkCompletionCreateWithoutUserInput[] | Prisma.HomeworkCompletionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.HomeworkCompletionCreateOrConnectWithoutUserInput | Prisma.HomeworkCompletionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.HomeworkCompletionCreateManyUserInputEnvelope
  connect?: Prisma.HomeworkCompletionWhereUniqueInput | Prisma.HomeworkCompletionWhereUniqueInput[]
}

export type HomeworkCompletionUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.HomeworkCompletionCreateWithoutUserInput, Prisma.HomeworkCompletionUncheckedCreateWithoutUserInput> | Prisma.HomeworkCompletionCreateWithoutUserInput[] | Prisma.HomeworkCompletionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.HomeworkCompletionCreateOrConnectWithoutUserInput | Prisma.HomeworkCompletionCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.HomeworkCompletionCreateManyUserInputEnvelope
  connect?: Prisma.HomeworkCompletionWhereUniqueInput | Prisma.HomeworkCompletionWhereUniqueInput[]
}

export type HomeworkCompletionUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.HomeworkCompletionCreateWithoutUserInput, Prisma.HomeworkCompletionUncheckedCreateWithoutUserInput> | Prisma.HomeworkCompletionCreateWithoutUserInput[] | Prisma.HomeworkCompletionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.HomeworkCompletionCreateOrConnectWithoutUserInput | Prisma.HomeworkCompletionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.HomeworkCompletionUpsertWithWhereUniqueWithoutUserInput | Prisma.HomeworkCompletionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.HomeworkCompletionCreateManyUserInputEnvelope
  set?: Prisma.HomeworkCompletionWhereUniqueInput | Prisma.HomeworkCompletionWhereUniqueInput[]
  disconnect?: Prisma.HomeworkCompletionWhereUniqueInput | Prisma.HomeworkCompletionWhereUniqueInput[]
  delete?: Prisma.HomeworkCompletionWhereUniqueInput | Prisma.HomeworkCompletionWhereUniqueInput[]
  connect?: Prisma.HomeworkCompletionWhereUniqueInput | Prisma.HomeworkCompletionWhereUniqueInput[]
  update?: Prisma.HomeworkCompletionUpdateWithWhereUniqueWithoutUserInput | Prisma.HomeworkCompletionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.HomeworkCompletionUpdateManyWithWhereWithoutUserInput | Prisma.HomeworkCompletionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.HomeworkCompletionScalarWhereInput | Prisma.HomeworkCompletionScalarWhereInput[]
}

export type HomeworkCompletionUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.HomeworkCompletionCreateWithoutUserInput, Prisma.HomeworkCompletionUncheckedCreateWithoutUserInput> | Prisma.HomeworkCompletionCreateWithoutUserInput[] | Prisma.HomeworkCompletionUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.HomeworkCompletionCreateOrConnectWithoutUserInput | Prisma.HomeworkCompletionCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.HomeworkCompletionUpsertWithWhereUniqueWithoutUserInput | Prisma.HomeworkCompletionUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.HomeworkCompletionCreateManyUserInputEnvelope
  set?: Prisma.HomeworkCompletionWhereUniqueInput | Prisma.HomeworkCompletionWhereUniqueInput[]
  disconnect?: Prisma.HomeworkCompletionWhereUniqueInput | Prisma.HomeworkCompletionWhereUniqueInput[]
  delete?: Prisma.HomeworkCompletionWhereUniqueInput | Prisma.HomeworkCompletionWhereUniqueInput[]
  connect?: Prisma.HomeworkCompletionWhereUniqueInput | Prisma.HomeworkCompletionWhereUniqueInput[]
  update?: Prisma.HomeworkCompletionUpdateWithWhereUniqueWithoutUserInput | Prisma.HomeworkCompletionUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.HomeworkCompletionUpdateManyWithWhereWithoutUserInput | Prisma.HomeworkCompletionUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.HomeworkCompletionScalarWhereInput | Prisma.HomeworkCompletionScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type HomeworkCompletionCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  clientId?: string | null
  seasonNumber: number
  episodeNumber: number
  itemIndex: number
}

export type HomeworkCompletionUncheckedCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  clientId?: string | null
  seasonNumber: number
  episodeNumber: number
  itemIndex: number
}

export type HomeworkCompletionCreateOrConnectWithoutUserInput = {
  where: Prisma.HomeworkCompletionWhereUniqueInput
  create: Prisma.XOR<Prisma.HomeworkCompletionCreateWithoutUserInput, Prisma.HomeworkCompletionUncheckedCreateWithoutUserInput>
}

export type HomeworkCompletionCreateManyUserInputEnvelope = {
  data: Prisma.HomeworkCompletionCreateManyUserInput | Prisma.HomeworkCompletionCreateManyUserInput[]
}

export type HomeworkCompletionUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.HomeworkCompletionWhereUniqueInput
  update: Prisma.XOR<Prisma.HomeworkCompletionUpdateWithoutUserInput, Prisma.HomeworkCompletionUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.HomeworkCompletionCreateWithoutUserInput, Prisma.HomeworkCompletionUncheckedCreateWithoutUserInput>
}

export type HomeworkCompletionUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.HomeworkCompletionWhereUniqueInput
  data: Prisma.XOR<Prisma.HomeworkCompletionUpdateWithoutUserInput, Prisma.HomeworkCompletionUncheckedUpdateWithoutUserInput>
}

export type HomeworkCompletionUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.HomeworkCompletionScalarWhereInput
  data: Prisma.XOR<Prisma.HomeworkCompletionUpdateManyMutationInput, Prisma.HomeworkCompletionUncheckedUpdateManyWithoutUserInput>
}

export type HomeworkCompletionScalarWhereInput = {
  AND?: Prisma.HomeworkCompletionScalarWhereInput | Prisma.HomeworkCompletionScalarWhereInput[]
  OR?: Prisma.HomeworkCompletionScalarWhereInput[]
  NOT?: Prisma.HomeworkCompletionScalarWhereInput | Prisma.HomeworkCompletionScalarWhereInput[]
  id?: Prisma.StringFilter<"HomeworkCompletion"> | string
  createdAt?: Prisma.DateTimeFilter<"HomeworkCompletion"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"HomeworkCompletion"> | Date | string
  userId?: Prisma.StringNullableFilter<"HomeworkCompletion"> | string | null
  clientId?: Prisma.StringNullableFilter<"HomeworkCompletion"> | string | null
  seasonNumber?: Prisma.IntFilter<"HomeworkCompletion"> | number
  episodeNumber?: Prisma.IntFilter<"HomeworkCompletion"> | number
  itemIndex?: Prisma.IntFilter<"HomeworkCompletion"> | number
}

export type HomeworkCompletionCreateManyUserInput = {
  id?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  clientId?: string | null
  seasonNumber: number
  episodeNumber: number
  itemIndex: number
}

export type HomeworkCompletionUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  clientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seasonNumber?: Prisma.IntFieldUpdateOperationsInput | number
  episodeNumber?: Prisma.IntFieldUpdateOperationsInput | number
  itemIndex?: Prisma.IntFieldUpdateOperationsInput | number
}

export type HomeworkCompletionUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  clientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seasonNumber?: Prisma.IntFieldUpdateOperationsInput | number
  episodeNumber?: Prisma.IntFieldUpdateOperationsInput | number
  itemIndex?: Prisma.IntFieldUpdateOperationsInput | number
}

export type HomeworkCompletionUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  clientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seasonNumber?: Prisma.IntFieldUpdateOperationsInput | number
  episodeNumber?: Prisma.IntFieldUpdateOperationsInput | number
  itemIndex?: Prisma.IntFieldUpdateOperationsInput | number
}



export type HomeworkCompletionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  clientId?: boolean
  seasonNumber?: boolean
  episodeNumber?: boolean
  itemIndex?: boolean
  user?: boolean | Prisma.HomeworkCompletion$userArgs<ExtArgs>
}, ExtArgs["result"]["homeworkCompletion"]>

export type HomeworkCompletionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  clientId?: boolean
  seasonNumber?: boolean
  episodeNumber?: boolean
  itemIndex?: boolean
  user?: boolean | Prisma.HomeworkCompletion$userArgs<ExtArgs>
}, ExtArgs["result"]["homeworkCompletion"]>

export type HomeworkCompletionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  clientId?: boolean
  seasonNumber?: boolean
  episodeNumber?: boolean
  itemIndex?: boolean
  user?: boolean | Prisma.HomeworkCompletion$userArgs<ExtArgs>
}, ExtArgs["result"]["homeworkCompletion"]>

export type HomeworkCompletionSelectScalar = {
  id?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  userId?: boolean
  clientId?: boolean
  seasonNumber?: boolean
  episodeNumber?: boolean
  itemIndex?: boolean
}

export type HomeworkCompletionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "updatedAt" | "userId" | "clientId" | "seasonNumber" | "episodeNumber" | "itemIndex", ExtArgs["result"]["homeworkCompletion"]>
export type HomeworkCompletionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.HomeworkCompletion$userArgs<ExtArgs>
}
export type HomeworkCompletionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.HomeworkCompletion$userArgs<ExtArgs>
}
export type HomeworkCompletionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.HomeworkCompletion$userArgs<ExtArgs>
}

export type $HomeworkCompletionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "HomeworkCompletion"
  objects: {
    user: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    createdAt: Date
    updatedAt: Date
    userId: string | null
    clientId: string | null
    seasonNumber: number
    episodeNumber: number
    itemIndex: number
  }, ExtArgs["result"]["homeworkCompletion"]>
  composites: {}
}

export type HomeworkCompletionGetPayload<S extends boolean | null | undefined | HomeworkCompletionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$HomeworkCompletionPayload, S>

export type HomeworkCompletionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<HomeworkCompletionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: HomeworkCompletionCountAggregateInputType | true
  }

export interface HomeworkCompletionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['HomeworkCompletion'], meta: { name: 'HomeworkCompletion' } }
  /**
   * Find zero or one HomeworkCompletion that matches the filter.
   * @param {HomeworkCompletionFindUniqueArgs} args - Arguments to find a HomeworkCompletion
   * @example
   * // Get one HomeworkCompletion
   * const homeworkCompletion = await prisma.homeworkCompletion.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends HomeworkCompletionFindUniqueArgs>(args: Prisma.SelectSubset<T, HomeworkCompletionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__HomeworkCompletionClient<runtime.Types.Result.GetResult<Prisma.$HomeworkCompletionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one HomeworkCompletion that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {HomeworkCompletionFindUniqueOrThrowArgs} args - Arguments to find a HomeworkCompletion
   * @example
   * // Get one HomeworkCompletion
   * const homeworkCompletion = await prisma.homeworkCompletion.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends HomeworkCompletionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, HomeworkCompletionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__HomeworkCompletionClient<runtime.Types.Result.GetResult<Prisma.$HomeworkCompletionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first HomeworkCompletion that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HomeworkCompletionFindFirstArgs} args - Arguments to find a HomeworkCompletion
   * @example
   * // Get one HomeworkCompletion
   * const homeworkCompletion = await prisma.homeworkCompletion.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends HomeworkCompletionFindFirstArgs>(args?: Prisma.SelectSubset<T, HomeworkCompletionFindFirstArgs<ExtArgs>>): Prisma.Prisma__HomeworkCompletionClient<runtime.Types.Result.GetResult<Prisma.$HomeworkCompletionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first HomeworkCompletion that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HomeworkCompletionFindFirstOrThrowArgs} args - Arguments to find a HomeworkCompletion
   * @example
   * // Get one HomeworkCompletion
   * const homeworkCompletion = await prisma.homeworkCompletion.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends HomeworkCompletionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, HomeworkCompletionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__HomeworkCompletionClient<runtime.Types.Result.GetResult<Prisma.$HomeworkCompletionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more HomeworkCompletions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HomeworkCompletionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all HomeworkCompletions
   * const homeworkCompletions = await prisma.homeworkCompletion.findMany()
   * 
   * // Get first 10 HomeworkCompletions
   * const homeworkCompletions = await prisma.homeworkCompletion.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const homeworkCompletionWithIdOnly = await prisma.homeworkCompletion.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends HomeworkCompletionFindManyArgs>(args?: Prisma.SelectSubset<T, HomeworkCompletionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HomeworkCompletionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a HomeworkCompletion.
   * @param {HomeworkCompletionCreateArgs} args - Arguments to create a HomeworkCompletion.
   * @example
   * // Create one HomeworkCompletion
   * const HomeworkCompletion = await prisma.homeworkCompletion.create({
   *   data: {
   *     // ... data to create a HomeworkCompletion
   *   }
   * })
   * 
   */
  create<T extends HomeworkCompletionCreateArgs>(args: Prisma.SelectSubset<T, HomeworkCompletionCreateArgs<ExtArgs>>): Prisma.Prisma__HomeworkCompletionClient<runtime.Types.Result.GetResult<Prisma.$HomeworkCompletionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many HomeworkCompletions.
   * @param {HomeworkCompletionCreateManyArgs} args - Arguments to create many HomeworkCompletions.
   * @example
   * // Create many HomeworkCompletions
   * const homeworkCompletion = await prisma.homeworkCompletion.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends HomeworkCompletionCreateManyArgs>(args?: Prisma.SelectSubset<T, HomeworkCompletionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many HomeworkCompletions and returns the data saved in the database.
   * @param {HomeworkCompletionCreateManyAndReturnArgs} args - Arguments to create many HomeworkCompletions.
   * @example
   * // Create many HomeworkCompletions
   * const homeworkCompletion = await prisma.homeworkCompletion.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many HomeworkCompletions and only return the `id`
   * const homeworkCompletionWithIdOnly = await prisma.homeworkCompletion.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends HomeworkCompletionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, HomeworkCompletionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HomeworkCompletionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a HomeworkCompletion.
   * @param {HomeworkCompletionDeleteArgs} args - Arguments to delete one HomeworkCompletion.
   * @example
   * // Delete one HomeworkCompletion
   * const HomeworkCompletion = await prisma.homeworkCompletion.delete({
   *   where: {
   *     // ... filter to delete one HomeworkCompletion
   *   }
   * })
   * 
   */
  delete<T extends HomeworkCompletionDeleteArgs>(args: Prisma.SelectSubset<T, HomeworkCompletionDeleteArgs<ExtArgs>>): Prisma.Prisma__HomeworkCompletionClient<runtime.Types.Result.GetResult<Prisma.$HomeworkCompletionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one HomeworkCompletion.
   * @param {HomeworkCompletionUpdateArgs} args - Arguments to update one HomeworkCompletion.
   * @example
   * // Update one HomeworkCompletion
   * const homeworkCompletion = await prisma.homeworkCompletion.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends HomeworkCompletionUpdateArgs>(args: Prisma.SelectSubset<T, HomeworkCompletionUpdateArgs<ExtArgs>>): Prisma.Prisma__HomeworkCompletionClient<runtime.Types.Result.GetResult<Prisma.$HomeworkCompletionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more HomeworkCompletions.
   * @param {HomeworkCompletionDeleteManyArgs} args - Arguments to filter HomeworkCompletions to delete.
   * @example
   * // Delete a few HomeworkCompletions
   * const { count } = await prisma.homeworkCompletion.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends HomeworkCompletionDeleteManyArgs>(args?: Prisma.SelectSubset<T, HomeworkCompletionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more HomeworkCompletions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HomeworkCompletionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many HomeworkCompletions
   * const homeworkCompletion = await prisma.homeworkCompletion.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends HomeworkCompletionUpdateManyArgs>(args: Prisma.SelectSubset<T, HomeworkCompletionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more HomeworkCompletions and returns the data updated in the database.
   * @param {HomeworkCompletionUpdateManyAndReturnArgs} args - Arguments to update many HomeworkCompletions.
   * @example
   * // Update many HomeworkCompletions
   * const homeworkCompletion = await prisma.homeworkCompletion.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more HomeworkCompletions and only return the `id`
   * const homeworkCompletionWithIdOnly = await prisma.homeworkCompletion.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends HomeworkCompletionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, HomeworkCompletionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HomeworkCompletionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one HomeworkCompletion.
   * @param {HomeworkCompletionUpsertArgs} args - Arguments to update or create a HomeworkCompletion.
   * @example
   * // Update or create a HomeworkCompletion
   * const homeworkCompletion = await prisma.homeworkCompletion.upsert({
   *   create: {
   *     // ... data to create a HomeworkCompletion
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the HomeworkCompletion we want to update
   *   }
   * })
   */
  upsert<T extends HomeworkCompletionUpsertArgs>(args: Prisma.SelectSubset<T, HomeworkCompletionUpsertArgs<ExtArgs>>): Prisma.Prisma__HomeworkCompletionClient<runtime.Types.Result.GetResult<Prisma.$HomeworkCompletionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of HomeworkCompletions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HomeworkCompletionCountArgs} args - Arguments to filter HomeworkCompletions to count.
   * @example
   * // Count the number of HomeworkCompletions
   * const count = await prisma.homeworkCompletion.count({
   *   where: {
   *     // ... the filter for the HomeworkCompletions we want to count
   *   }
   * })
  **/
  count<T extends HomeworkCompletionCountArgs>(
    args?: Prisma.Subset<T, HomeworkCompletionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], HomeworkCompletionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a HomeworkCompletion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HomeworkCompletionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends HomeworkCompletionAggregateArgs>(args: Prisma.Subset<T, HomeworkCompletionAggregateArgs>): Prisma.PrismaPromise<GetHomeworkCompletionAggregateType<T>>

  /**
   * Group by HomeworkCompletion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HomeworkCompletionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends HomeworkCompletionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: HomeworkCompletionGroupByArgs['orderBy'] }
      : { orderBy?: HomeworkCompletionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, HomeworkCompletionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetHomeworkCompletionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the HomeworkCompletion model
 */
readonly fields: HomeworkCompletionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for HomeworkCompletion.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__HomeworkCompletionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.HomeworkCompletion$userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.HomeworkCompletion$userArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the HomeworkCompletion model
 */
export interface HomeworkCompletionFieldRefs {
  readonly id: Prisma.FieldRef<"HomeworkCompletion", 'String'>
  readonly createdAt: Prisma.FieldRef<"HomeworkCompletion", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"HomeworkCompletion", 'DateTime'>
  readonly userId: Prisma.FieldRef<"HomeworkCompletion", 'String'>
  readonly clientId: Prisma.FieldRef<"HomeworkCompletion", 'String'>
  readonly seasonNumber: Prisma.FieldRef<"HomeworkCompletion", 'Int'>
  readonly episodeNumber: Prisma.FieldRef<"HomeworkCompletion", 'Int'>
  readonly itemIndex: Prisma.FieldRef<"HomeworkCompletion", 'Int'>
}
    

// Custom InputTypes
/**
 * HomeworkCompletion findUnique
 */
export type HomeworkCompletionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HomeworkCompletion
   */
  select?: Prisma.HomeworkCompletionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HomeworkCompletion
   */
  omit?: Prisma.HomeworkCompletionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomeworkCompletionInclude<ExtArgs> | null
  /**
   * Filter, which HomeworkCompletion to fetch.
   */
  where: Prisma.HomeworkCompletionWhereUniqueInput
}

/**
 * HomeworkCompletion findUniqueOrThrow
 */
export type HomeworkCompletionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HomeworkCompletion
   */
  select?: Prisma.HomeworkCompletionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HomeworkCompletion
   */
  omit?: Prisma.HomeworkCompletionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomeworkCompletionInclude<ExtArgs> | null
  /**
   * Filter, which HomeworkCompletion to fetch.
   */
  where: Prisma.HomeworkCompletionWhereUniqueInput
}

/**
 * HomeworkCompletion findFirst
 */
export type HomeworkCompletionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HomeworkCompletion
   */
  select?: Prisma.HomeworkCompletionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HomeworkCompletion
   */
  omit?: Prisma.HomeworkCompletionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomeworkCompletionInclude<ExtArgs> | null
  /**
   * Filter, which HomeworkCompletion to fetch.
   */
  where?: Prisma.HomeworkCompletionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HomeworkCompletions to fetch.
   */
  orderBy?: Prisma.HomeworkCompletionOrderByWithRelationInput | Prisma.HomeworkCompletionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for HomeworkCompletions.
   */
  cursor?: Prisma.HomeworkCompletionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HomeworkCompletions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HomeworkCompletions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of HomeworkCompletions.
   */
  distinct?: Prisma.HomeworkCompletionScalarFieldEnum | Prisma.HomeworkCompletionScalarFieldEnum[]
}

/**
 * HomeworkCompletion findFirstOrThrow
 */
export type HomeworkCompletionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HomeworkCompletion
   */
  select?: Prisma.HomeworkCompletionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HomeworkCompletion
   */
  omit?: Prisma.HomeworkCompletionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomeworkCompletionInclude<ExtArgs> | null
  /**
   * Filter, which HomeworkCompletion to fetch.
   */
  where?: Prisma.HomeworkCompletionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HomeworkCompletions to fetch.
   */
  orderBy?: Prisma.HomeworkCompletionOrderByWithRelationInput | Prisma.HomeworkCompletionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for HomeworkCompletions.
   */
  cursor?: Prisma.HomeworkCompletionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HomeworkCompletions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HomeworkCompletions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of HomeworkCompletions.
   */
  distinct?: Prisma.HomeworkCompletionScalarFieldEnum | Prisma.HomeworkCompletionScalarFieldEnum[]
}

/**
 * HomeworkCompletion findMany
 */
export type HomeworkCompletionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HomeworkCompletion
   */
  select?: Prisma.HomeworkCompletionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HomeworkCompletion
   */
  omit?: Prisma.HomeworkCompletionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomeworkCompletionInclude<ExtArgs> | null
  /**
   * Filter, which HomeworkCompletions to fetch.
   */
  where?: Prisma.HomeworkCompletionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HomeworkCompletions to fetch.
   */
  orderBy?: Prisma.HomeworkCompletionOrderByWithRelationInput | Prisma.HomeworkCompletionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing HomeworkCompletions.
   */
  cursor?: Prisma.HomeworkCompletionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HomeworkCompletions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HomeworkCompletions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of HomeworkCompletions.
   */
  distinct?: Prisma.HomeworkCompletionScalarFieldEnum | Prisma.HomeworkCompletionScalarFieldEnum[]
}

/**
 * HomeworkCompletion create
 */
export type HomeworkCompletionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HomeworkCompletion
   */
  select?: Prisma.HomeworkCompletionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HomeworkCompletion
   */
  omit?: Prisma.HomeworkCompletionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomeworkCompletionInclude<ExtArgs> | null
  /**
   * The data needed to create a HomeworkCompletion.
   */
  data: Prisma.XOR<Prisma.HomeworkCompletionCreateInput, Prisma.HomeworkCompletionUncheckedCreateInput>
}

/**
 * HomeworkCompletion createMany
 */
export type HomeworkCompletionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many HomeworkCompletions.
   */
  data: Prisma.HomeworkCompletionCreateManyInput | Prisma.HomeworkCompletionCreateManyInput[]
}

/**
 * HomeworkCompletion createManyAndReturn
 */
export type HomeworkCompletionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HomeworkCompletion
   */
  select?: Prisma.HomeworkCompletionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the HomeworkCompletion
   */
  omit?: Prisma.HomeworkCompletionOmit<ExtArgs> | null
  /**
   * The data used to create many HomeworkCompletions.
   */
  data: Prisma.HomeworkCompletionCreateManyInput | Prisma.HomeworkCompletionCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomeworkCompletionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * HomeworkCompletion update
 */
export type HomeworkCompletionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HomeworkCompletion
   */
  select?: Prisma.HomeworkCompletionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HomeworkCompletion
   */
  omit?: Prisma.HomeworkCompletionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomeworkCompletionInclude<ExtArgs> | null
  /**
   * The data needed to update a HomeworkCompletion.
   */
  data: Prisma.XOR<Prisma.HomeworkCompletionUpdateInput, Prisma.HomeworkCompletionUncheckedUpdateInput>
  /**
   * Choose, which HomeworkCompletion to update.
   */
  where: Prisma.HomeworkCompletionWhereUniqueInput
}

/**
 * HomeworkCompletion updateMany
 */
export type HomeworkCompletionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update HomeworkCompletions.
   */
  data: Prisma.XOR<Prisma.HomeworkCompletionUpdateManyMutationInput, Prisma.HomeworkCompletionUncheckedUpdateManyInput>
  /**
   * Filter which HomeworkCompletions to update
   */
  where?: Prisma.HomeworkCompletionWhereInput
  /**
   * Limit how many HomeworkCompletions to update.
   */
  limit?: number
}

/**
 * HomeworkCompletion updateManyAndReturn
 */
export type HomeworkCompletionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HomeworkCompletion
   */
  select?: Prisma.HomeworkCompletionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the HomeworkCompletion
   */
  omit?: Prisma.HomeworkCompletionOmit<ExtArgs> | null
  /**
   * The data used to update HomeworkCompletions.
   */
  data: Prisma.XOR<Prisma.HomeworkCompletionUpdateManyMutationInput, Prisma.HomeworkCompletionUncheckedUpdateManyInput>
  /**
   * Filter which HomeworkCompletions to update
   */
  where?: Prisma.HomeworkCompletionWhereInput
  /**
   * Limit how many HomeworkCompletions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomeworkCompletionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * HomeworkCompletion upsert
 */
export type HomeworkCompletionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HomeworkCompletion
   */
  select?: Prisma.HomeworkCompletionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HomeworkCompletion
   */
  omit?: Prisma.HomeworkCompletionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomeworkCompletionInclude<ExtArgs> | null
  /**
   * The filter to search for the HomeworkCompletion to update in case it exists.
   */
  where: Prisma.HomeworkCompletionWhereUniqueInput
  /**
   * In case the HomeworkCompletion found by the `where` argument doesn't exist, create a new HomeworkCompletion with this data.
   */
  create: Prisma.XOR<Prisma.HomeworkCompletionCreateInput, Prisma.HomeworkCompletionUncheckedCreateInput>
  /**
   * In case the HomeworkCompletion was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.HomeworkCompletionUpdateInput, Prisma.HomeworkCompletionUncheckedUpdateInput>
}

/**
 * HomeworkCompletion delete
 */
export type HomeworkCompletionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HomeworkCompletion
   */
  select?: Prisma.HomeworkCompletionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HomeworkCompletion
   */
  omit?: Prisma.HomeworkCompletionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomeworkCompletionInclude<ExtArgs> | null
  /**
   * Filter which HomeworkCompletion to delete.
   */
  where: Prisma.HomeworkCompletionWhereUniqueInput
}

/**
 * HomeworkCompletion deleteMany
 */
export type HomeworkCompletionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which HomeworkCompletions to delete
   */
  where?: Prisma.HomeworkCompletionWhereInput
  /**
   * Limit how many HomeworkCompletions to delete.
   */
  limit?: number
}

/**
 * HomeworkCompletion.user
 */
export type HomeworkCompletion$userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * HomeworkCompletion without action
 */
export type HomeworkCompletionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HomeworkCompletion
   */
  select?: Prisma.HomeworkCompletionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HomeworkCompletion
   */
  omit?: Prisma.HomeworkCompletionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HomeworkCompletionInclude<ExtArgs> | null
}
